#!/usr/bin/env python3
"""Generate the LaTeX fragments the methods documents include — every
number from the manifest or from a parity run, never typed.

Writes into Docs/Methods/generated/:
  terms-macros.tex      \\term{key} → the term's name, hyperlinked to its entry
  glossary.tex          the technical glossary (methods.tex)
  glossary-plain.tex    the plain-language glossary (explained.tex)
  parameters-hd.tex     the Harmonic Distortion parameter table
  windows-hd.tex        the per-order delay / window / validity table
  plain-hd.tex          the lay companion's number macros and per-harmonic table
                        (plus the words form of every scalar in parity-hd.tex)
  parity-hd.tex         the parity run's numbers (needs the Swift tool;
                        skipped with --no-parity, in which case the
                        committed file is left alone)
  parameters-transfer.tex  the Transfer Curve parameter table (#306)
  parity-transfer.tex   the transfer parity run's numbers (same rule)
  parameters-imd.tex    the Chord IMD parameter table (#306 chapter three)
  lattice-imd.tex       the lattice the shipped search chose on every grid, the
                        window on every grid, and the fifth's harmonic-role grid
  parity-imd.tex        the Chord IMD parity run's numbers (same rule)
  plain-transfer.tex    the lay companion's Transfer Curve macros (#307), and
                        the words form of every scalar in parity-transfer.tex
  plain-imd.tex         the lay companion's Chord IMD macros (#307 chapter three),
                        and the words form of every scalar in parity-imd.tex
  parameters-journey.tex  the Gain Map parameter table (#306 chapter four)
  residue-journey.tex   the analyzer's residue per column per sweep length on the
                        shipped grid, and the leakage map, from the manifest
  parity-journey.tex    the Gain Map parity run's numbers (same rule)
"""
from __future__ import annotations

import argparse
import json
import math
import os
import re
import sys

import yaml

import harmonic_distortion as hd

HERE = os.path.dirname(os.path.abspath(__file__))
METHODS = os.path.normpath(os.path.join(HERE, ".."))
GENERATED = os.path.join(METHODS, "generated")
TERMS = os.path.join(METHODS, "terms.yaml")


def tex_escape(s: str) -> str:
    return (s.replace("\\", r"\textbackslash{}").replace("&", r"\&").replace("%", r"\%")
             .replace("$", r"\$").replace("#", r"\#").replace("_", r"\_").replace("{", r"\{")
             .replace("}", r"\}").replace("~", r"\textasciitilde{}").replace("^", r"\textasciicircum{}"))


def num(v, sig=6) -> str:
    if isinstance(v, bool):
        return "yes" if v else "no"
    if isinstance(v, int):
        return f"{v:,}".replace(",", r"\,")
    if v is None:
        return "--"
    if isinstance(v, float):
        if math.isinf(v):
            return r"$-\infty$" if v < 0 else r"$\infty$"
        if v == int(v) and abs(v) < 1e15:
            return f"{int(v):,}".replace(",", r"\,")
        return f"{v:.{sig}g}"
    return tex_escape(str(v))


def load_terms():
    with open(TERMS, encoding="utf-8") as f:
        data = yaml.safe_load(f)
    terms = data["terms"]
    keys = [t["key"] for t in terms]
    assert len(keys) == len(set(keys)), "duplicate term keys"
    for t in terms:
        for field in ("key", "term", "technical", "plain"):
            assert t.get(field), f"term {t.get('key')!r} lacks {field}"
        assert re.fullmatch(r"[a-z][a-z0-9-]*", t["key"]), f"bad key {t['key']!r}"
    return terms


def write(path, text):
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)


def gen_terms(terms):
    macros = ["% GENERATED by gen_docs.py from terms.yaml — do not edit\n"]
    for t in terms:
        macros.append(r"\expandafter\newcommand\csname term@%s\endcsname{%s}" % (t["key"], t["term"]) + "\n")
    write(os.path.join(GENERATED, "terms-macros.tex"), "".join(macros))

    def entry(t, plain):
        sym = f" ({t['symbol']})" if t.get("symbol") else ""
        body = t["plain"] if plain else t["technical"]
        return (r"\item[{\hypertarget{term:%s}{%s}%s}] %s"
                % (t["key"], t["term"], sym, body) + "\n")

    ordered = sorted(terms, key=lambda t: t["term"].lower())
    for name, plain in (("glossary.tex", False), ("glossary-plain.tex", True)):
        out = ["% GENERATED by gen_docs.py from terms.yaml — do not edit\n",
               r"\begin{description}" + "\n"]
        out += [entry(t, plain) for t in ordered]
        out.append(r"\end{description}" + "\n")
        write(os.path.join(GENERATED, name), "".join(out))


def gen_parameters(m):
    st, ex, rd, va, gr, fl, av, pr, sh, sy = (m[k] for k in (
        "stimulus", "extraction", "reading", "validity", "grids", "floor", "averaging",
        "fundamentalPresence", "shaping", "synthesis"))
    rows = [
        ("Stimulus", None),
        (r"start frequency $f_1$", num(st["startHz"]) + " Hz"),
        (r"end frequency $f_2$", num(st["endHz"]) + " Hz"),
        (r"requested duration $\hat T$", num(st["requestedDurationS"]) + " s"),
        (r"sample rate $f_s$", num(st["sampleRateHz"]) + " Hz"),
        (r"amplitude $A$ (re full scale)", num(st["amplitude"])),
        (r"rate constant $L$", num(st["rateConstantS"]) + " s"),
        (r"synchronization cycles $f_1 L$", num(st["synchronizationCycles"])),
        (r"actual duration $T = L\ln(f_2/f_1)$", num(st["durationS"], 10) + " s"),
        (r"sample count", num(st["sampleCount"])),
        (r"fade-in / fade-out", num(st["fadeInS"]) + " s / " + num(st["fadeOutS"]) + " s"),
        (r"excited band (fade edges)", num(st["excitedBandBottomHz"], 5) + " Hz -- " + num(st["excitedBandTopHz"], 5) + " Hz"),
        ("Deconvolution", None),
        (r"inverse-filter taper", num(m["deconvolution"]["taperLowHz"]) + " Hz -- " + num(m["deconvolution"]["taperHighHz"]) + " Hz"),
        (r"DFT length $N$ for one synth capture", num(m["deconvolution"]["fftLengthForSynthCapture"])),
        ("Extraction", None),
        (r"harmonic count $K$", num(ex["harmonicCount"])),
        (r"response DFT length $M$", num(ex["responseFFTLength"])),
        (r"window half-width cap", num(ex["maxWindowHalfWidthS"]) + " s"),
        (r"minimum half-width", num(int(re.search(r"\b(\d+) samples", ex["minimumHalfWidthRule"]).group(1))) + " samples (a literal in the analyzer)"),
        (r"bin width $f_s/M$", num(rd["binWidthHz"], 8) + " Hz"),
        (r"bins per response", num(rd["binCount"])),
        ("Grids", None),
        (r"distance grid (\S 11)", f"{num(gr['distance']['pointCount'])} log-spaced points, {num(gr['distance']['lowHz'],4)}--{num(gr['distance']['highHz'])} Hz"),
        (r"THD curve grid", f"{num(gr['thdCurve']['pointCount'])} of {num(gr['thdCurve']['requestedPointCount'])} requested, {num(gr['thdCurve']['lowHz'],4)}--{num(gr['thdCurve']['highHz'],6)} Hz"),
        (r"oracle grid (\texttt{synth})", f"{num(gr['synth']['pointCount'])} points, {num(gr['synth']['lowHz'],4)}--{num(gr['synth']['highHz'])} Hz"),
        (r"distance fixed floor clamp", num(gr["distanceFloorClampDB"]) + " dB"),
        (r"distance minimum resolved share", num(gr["distanceMinimumResolvedShare"])),
        (r"audible band", num(m["audibleBand"]["lowHz"]) + " Hz -- " + num(m["audibleBand"]["highHz"]) + " Hz"),
        ("Floor", None),
        (r"calibration analyzed sweeps $N_{\mathrm{cal}}$", num(fl["calibrationAnalyzedSweepCount"])),
        (r"averaging term at 1 / 2 / 4 / 8 sweeps", " / ".join(num(fl["averagingAdjustmentDB"][k], 4) + " dB" for k in ("1", "2", "4", "8"))),
        (r"stamp read (median points)", num(fl["stampReadMedianPoints"])),
        (r"at-floor epsilon", num(fl["atFloorEpsilonDB"]) + " dB"),
        ("Averaging", None),
        (r"default / offered sweep counts", num(av["defaultAverages"]) + " / " + ", ".join(num(x) for x in av["offeredAverages"])),
        (r"pre-roll / gap / tail", f"{num(av['prerollS'])} s / {num(av['interSweepGapS'])} s / {num(av['tailS'])} s"),
        (r"delay fit: samples per order", num(av["delayFitSampleCount"])),
        (r"delay fit: scan limit / coarse / fine", f"$\\pm${num(av['delayScanLimitSamples'])} / {num(av['delayCoarseStepSamples'])} / {num(av['delayFineStepSamples'])} samples"),
        ("Fundamental presence", None),
        (r"analyzer separation bound", num(pr["analyzerSeparationDB"]) + " dB"),
        (r"verdict grid points", num(pr["verdictGridPoints"])),
        ("Shaping", None),
        (r"window samples", num(sh["windowSampleCount"])),
        (r"pure-noise coherence $1/\sqrt{n}$", num(sh["unshapedCoherence"], 5)),
        (r"decorrelation factor", num(sh["decorrelationFactor"])),
        (r"shaped SNR bar", num(sh["shapedSNRDB"]) + " dB"),
        (r"unshaped scatter", num(sh["unshapedScatterDB"], 5) + " dB"),
        ("Summaries", None),
        (r"lexicon version", tex_escape(m["summaryLexiconVersion"])),
        ("Oracle (\\texttt{analysisdump synth})", None),
        (r"post-sweep pad", num(sy["padSamples"]) + " samples"),
        (r"phantom Nyquist gate", num(sy["phantomNyquistGateFraction"]) + r" $\times f_s/2$"),
        (r"ground-truth quadrature points", num(sy["groundTruthPoints"])),
        (r"noise generator increment", r"\texttt{" + tex_escape(sy["noiseGeneratorIncrement"]) + "}"),
    ]
    out = ["% GENERATED by gen_docs.py from generated/manifest.json — do not edit\n",
           r"\begin{longtable}{@{}p{0.5\linewidth}p{0.45\linewidth}@{}}" + "\n",
           r"\toprule Parameter & Value \\ \midrule \endhead" + "\n"]
    for label, value in rows:
        if value is None:
            out.append(r"\multicolumn{2}{@{}l}{\textbf{%s}} \\" % label + "\n")
        else:
            out.append(f"{label} & {value} \\\\\n")
    out.append(r"\bottomrule" + "\n" + r"\end{longtable}" + "\n")
    write(os.path.join(GENERATED, "parameters-hd.tex"), "".join(out))


def gen_windows(m):
    ex = m["extraction"]
    va = m["validity"]
    fs = m["stimulus"]["sampleRateHz"]
    out = ["% GENERATED by gen_docs.py from generated/manifest.json — do not edit\n",
           r"\begin{tabular}{@{}rrrrr@{}}" + "\n",
           r"\toprule $k$ & $\Delta t_k = L\ln k$ (s) & window $T_k$ (s) & window (samples) & $\max f_0$ valid (Hz) \\ \midrule" + "\n"]
    for row, top in zip(ex["windows"], va["maxValidFundamentalHz"]):
        out.append(f"{row['order']} & {num(row['delayS'], 6)} & {num(row['windowS'], 6)} & {num(int(round(row['windowS'] * fs)))} & {num(top, 6)} \\\\\n")
    out.append(r"\bottomrule" + "\n" + r"\end{tabular}" + "\n")
    write(os.path.join(GENERATED, "windows-hd.tex"), "".join(out))


def gen_parity(m):
    import parity_hd as P
    tool = P.build_tool()
    out = ["% GENERATED by gen_docs.py from a parity run (Swift vs Python vs analytic) — do not edit\n"]
    out.append(r"\newcommand{\paritySwiftTolerance}{%s}" % num(P.T_SWIFT, 3) + "\n")
    out.append(r"\newcommand{\parityAliasFreeTolerance}{%s}" % num(P.T_ANALYTIC_ALIAS_FREE, 3) + "\n")
    out.append(r"\newcommand{\parityPerSampleTolerances}{%s}" % ", ".join(
        f"{tex_escape(k)} {num(v, 3)} dB" for k, v in P.T_ANALYTIC_PER_SAMPLE.items()) + "\n")
    out.append(r"\newcommand{\parityEmptyDepth}{%s}" % num(P.EMPTY_ORDER_DEPTH_DB, 3) + "\n")
    out.append(r"\newcommand{\parityScatterMultiple}{%s}" % num(P.NOISY_SCATTER_MULTIPLE, 3) + "\n")
    cases = list(P.CASES)
    reports = {}
    twins = {}
    for case in cases:
        swift = P.run_swift(tool, case)
        reports[case.name] = P.compare(case, swift, P.run_python(case), m)
        if case.source != "phantom":
            twin = P.phantom_twin(case, swift)
            twins[case.name] = P.compare(twin, P.run_swift(tool, twin), P.run_python(twin), m)
    noisy = P.compare(P.NOISY, P.run_swift(tool, P.NOISY), P.run_python(P.NOISY), m)

    out.append(r"\newcommand{\parityTable}{" + "\n")
    out.append(r"\begin{longtable}{@{}p{0.2\linewidth}rrrrrr@{}}" + "\n")
    out.append(r"\toprule case & $k$ & expected & S$-$P & S$-$T band & P$-$T band & S$-$T full \\" + "\n")
    out.append(r" & & (dB) & (dB) & (dB) & (dB) & (dB) \\ \midrule \endhead" + "\n")
    for case in cases:
        r = reports[case.name]
        for o in r.content_orders():
            out.append(f"{tex_escape(case.name)} & {o.order} & {num(o.expected_db, 5)} & {num(o.max_swift_vs_python, 2)} & {num(o.max_swift_vs_analytic_band, 3)} & {num(o.max_python_vs_analytic_band, 3)} & {num(o.max_swift_vs_analytic_full, 3)} \\\\\n")
        if case.name in twins:
            for o in twins[case.name].content_orders():
                out.append(f"{tex_escape(case.name)} twin & {o.order} & {num(o.expected_db, 5)} & {num(o.max_swift_vs_python, 2)} & {num(o.max_swift_vs_analytic_band, 3)} & {num(o.max_python_vs_analytic_band, 3)} & {num(o.max_swift_vs_analytic_full, 3)} \\\\\n")
    out.append(r"\bottomrule" + "\n" + r"\end{longtable}" + "\n}\n")

    out.append(r"\newcommand{\parityNoisyTable}{" + "\n")
    out.append(r"\begin{tabular}{@{}rrrrrr@{}}" + "\n")
    out.append(r"\toprule $k$ & expected (dB) & shaped points & S$-$P (dB) & S$-$T shaped, band (dB) & error / allowance \\ \midrule" + "\n")
    for o in noisy.content_orders():
        out.append(f"{o.order} & {num(o.expected_db, 5)} & {o.shaped_both} & {num(o.max_swift_vs_python, 2)} & {num(o.max_swift_vs_analytic_band, 3)} & {num(o.max_scatter_normalized, 2)} \\\\\n")
    out.append(r"\bottomrule" + "\n" + r"\end{tabular}" + "\n}\n")

    tanh = reports["tanh"]
    o1 = next(o for o in tanh.content_orders() if o.order == 1)
    o3 = next(o for o in tanh.content_orders() if o.order == 3)
    o9 = next(o for o in tanh.content_orders() if o.order == 9)
    out.append(r"\newcommand{\parityTanhHone}{%s}" % num(o1.expected_db, 5) + "\n")
    out.append(r"\newcommand{\parityTanhHthree}{%s}" % num(o3.expected_db, 5) + "\n")
    out.append(r"\newcommand{\parityTanhHnine}{%s}" % num(o9.expected_db, 5) + "\n")
    out.append(r"\newcommand{\parityTanhFullBand}{%s}" % num(P.full_band_max(tanh), 3) + "\n")
    out.append(r"\newcommand{\parityHardclipFullBand}{%s}" % num(P.full_band_max(reports["hardclip"]), 3) + "\n")
    out.append(r"\newcommand{\parityWorstSwift}{%s}" % num(max(o.max_swift_vs_python for r in reports.values() for o in r.content_orders()), 2) + "\n")
    write(os.path.join(GENERATED, "parity-hd.tex"), "".join(out))


# --- The Transfer Curve chapter's fragments (#306) --------------------------


def deg(rad: float) -> str:
    return f"{math.degrees(rad):.1f}"


def gen_parameters_transfer(tc):
    st, bn, fg, mv, dr, o, pr, bq, sy = (tc[k] for k in (
        "stimulus", "binning", "figure", "memoryVerdict", "derotation", "orientation",
        "fundamentalPresence", "biquad", "synthesis"))
    coarse = re.search(r"steps of ([0-9.]+) samples", dr["frameFitRule"]).group(1)
    fine = re.search(r"in steps of ([0-9.]+);", dr["frameFitRule"]).group(1)
    skip5 = re.search(r"skipCycles (\d+)", st["analyzerDefaultSkipCyclesRule"]).group(1)
    rows = [
        ("Stimulus", None),
        (r"standard note / frequency $f_0$", tex_escape(st["defaultNote"]) + " / " + num(st["defaultFrequencyHz"]) + " Hz"),
        (r"standard amplitude $A$ (re full scale)", num(st["defaultAmplitude"]) + f" ({num(st['defaultLevelDBFS'], 4)} dBFS)"),
        (r"tone duration $T$ / pre-roll / tail", f"{num(st['durationS'])} s / {num(st['prerollS'])} s / {num(st['tailS'])} s"),
        (r"fade-in and fade-out $t_{\mathrm{fade}}$", num(st["fadeS"]) + " s"),
        (r"skipped cycles (the app's call)", num(st["skipCycles"]) + f" (the analyzer's own default is {skip5}, unused)"),
        (r"sample rate $f_s$ (the manifest's)", num(st["sampleRateHz"]) + " Hz"),
        (r"samples per cycle $P$ at $f_0$", num(st["samplesPerCycle"], 8)),
        (r"probe notes offered", ", ".join(tex_escape(n) for n in st["probeNotes"])),
        (r"note-range capture", ", ".join(tex_escape(n) for n in st["rangeNotes"])),
        (r"drive level bounds (hardware / plugin ceiling)", f"{num(st['levelFloorDBFS'])} to {num(st['levelCeilingDBFS'])} dBFS / {num(st['pluginLevelCeilingDBFS'])} dBFS"),
        ("Binning and the figure", None),
        (r"phase bins $n$", num(bn["phaseBins"])),
        (r"static-curve grid points", num(fg["staticCurveGridPoints"])),
        (r"lobe floor (fraction of the box)", num(fg["minimumLobeAreaFraction"])),
        ("Memory verdict (bisected from the shipped verdict)", None),
        (r"memoryless-ish below", num(mv["memorylessBelow"])),
        (r"memory effects from", num(mv["memoryEffectsFrom"])),
        (r"Phase removal (\S\,6.5)", None),
        (r"dead zone $\varepsilon$ (raw total area)", num(dr["deadZone"])),
        (r"pairing residual tolerance", num(dr["pairingResidualTolerance"]) + " rad"),
        (r"fit magnitude floor (both sides)", num(dr["fitMagnitudeFloor"]) + f" ({num(dr['fitMagnitudeFloorDB'], 3)} dB)"),
        (r"minimum fittable terms", num(dr["minimumFitTerms"])),
        (r"lattice sign confidence", num(dr["latticeSignConfidence"]) + " rad"),
        (r"metric-guard tolerance (decomposed areas)", num(dr["compensationLoopTolerance"])),
        (r"frame-fit scan: coarse / fine step", f"{coarse} / {fine} samples (literals)"),
        ("Orientation and polarity", None),
        (r"half-cycle lock tolerance", num(o["halfCycleLockTolerance"]) + " rad"),
        (r"polarity confidence threshold", num(o["polarityConfidenceThreshold"])),
        (r"polarity band", "20 Hz -- 2 kHz (literals)"),
        ("Fundamental presence", None),
        (r"analyzer separation bound", num(pr["analyzerSeparationDB"]) + " dB"),
        (r"Oracle (\texttt{analysisdump transfer-synth})", None),
        (r"biquad default $Q$", num(bq["defaultQ"], 8)),
        (r"truth series orders $K$", num(sy["truthOrders"])),
        (r"truth quadrature points", num(sy["quadraturePoints"])),
    ]
    out = ["% GENERATED by gen_docs.py from generated/manifest.json — do not edit\n",
           r"\begin{longtable}{@{}p{0.5\linewidth}p{0.45\linewidth}@{}}" + "\n",
           r"\toprule Parameter & Value \\ \midrule \endhead" + "\n"]
    for label, value in rows:
        if value is None:
            out.append(r"\multicolumn{2}{@{}l}{\textbf{%s}} \\" % label + "\n")
        else:
            out.append(f"{label} & {value} \\\\\n")
    out.append(r"\bottomrule" + "\n" + r"\end{longtable}" + "\n")
    write(os.path.join(GENERATED, "parameters-transfer.tex"), "".join(out))


def gen_parity_transfer(tc):
    import parity_transfer as P
    tool = P.build_tool()
    results = P.run_all(tool)
    reports = {name: P.compare(case, swift, python) for name, (case, swift, python) in results.items()}
    out = ["% GENERATED by gen_docs.py from a parity run (Swift vs Python vs closed-form truth) — do not edit\n"]
    out.append(r"\newcommand{\tparitySwift}{%s}" % num(P.T_SWIFT, 3) + "\n")
    out.append(r"\newcommand{\tparitySwiftShift}{%s}" % num(P.T_SWIFT_SHIFT, 3) + "\n")
    out.append(r"\newcommand{\tparityEllipseRatio}{%s}" % num(P.T_ELLIPSE_RATIO, 3) + "\n")
    out.append(r"\newcommand{\tparityEllipseRatioLong}{%s}" % num(P.T_ELLIPSE_RATIO_LONG, 3) + "\n")
    out.append(r"\newcommand{\tparityCompStatic}{%s}" % num(P.T_COMP_STATIC_TRUTH, 3) + "\n")
    out.append(r"\newcommand{\tparityCompCycle}{%s}" % num(P.T_COMP_CYCLE_TRUTH, 3) + "\n")
    out.append(r"\newcommand{\tparityFrameShift}{%s}" % num(P.T_FRAME_SHIFT_SAMPLES, 3) + "\n")
    out.append(r"\newcommand{\tparityResidual}{%s}" % num(P.T_RESIDUAL_RMS, 3) + "\n")
    out.append(r"\newcommand{\tparityCompArea}{%s}" % num(P.T_COMP_AREA, 3) + "\n")
    out.append(r"\newcommand{\tparityMemorylessNonlinear}{%s}" % num(P.T_MEMORYLESS_NONLINEAR, 3) + "\n")
    out.append(r"\newcommand{\tparityRawStaticSmooth}{%s}" % num(P.T_RAW_STATIC_TRUTH["memoryless"], 3) + "\n")
    out.append(r"\newcommand{\tparityRawStaticHardclip}{%s}" % num(P.T_RAW_STATIC_TRUTH["hardclip"], 3) + "\n")
    out.append(r"\newcommand{\tparityRawStaticEllipse}{%s}" % num(P.T_RAW_STATIC_TRUTH["ellipse"], 3) + "\n")
    out.append(r"\newcommand{\tparityCaseCount}{%d}" % len(P.CASES) + "\n")
    worst_swift = max(max(r.swift_cycle, r.swift_static, r.swift_areas, r.swift_psi1,
                          r.swift_compensated if r.has_compensated else 0.0,
                          r.swift_residual if math.isfinite(r.swift_residual) else 0.0,
                          r.swift_terms if math.isfinite(r.swift_terms) else 0.0) for r in reports.values())
    out.append(r"\newcommand{\tparityWorstSwift}{%s}" % num(worst_swift, 2) + "\n")
    out.append(r"\newcommand{\tparityWorstShift}{%s}" % num(max(r.swift_shift for r in reports.values() if math.isfinite(r.swift_shift)), 2) + "\n")

    # The ellipse table: (b) and (c), at 1.5 s and 15 s.
    out.append(r"\newcommand{\tparityEllipseTable}{" + "\n")
    out.append(r"\begin{tabular}{@{}lrrrrr@{}}" + "\n")
    out.append(r"\toprule case & $f_0$ (Hz) & $\varphi_1$ ($^\circ$) & measured & $(\pi/4)|\sin\varphi_1|$ & ratio \\ \midrule" + "\n")
    for name in ("b-lp-E2", "b-lp-A6", "b-lp-C7", "c-delay-E2", "c-delay-A4", "c-delay-C7",
                 "b-lp-E2-15s", "b-lp-A6-15s", "b-lp-C7-15s"):
        case, swift, _ = results[name]
        r = reports[name]
        d = P.parse(swift)
        phi = d.value("truth", "fundamental_phase")
        out.append(f"{tex_escape(name)} & {num(d.value('stimulus', 'f0_hz'), 5)} & {deg(phi)} & {num(r.linear, 5)} & {num(r.expected_linear, 5)} & {num(r.ellipse_ratio, 5)} \\\\\n")
    out.append(r"\bottomrule" + "\n" + r"\end{tabular}" + "\n}\n")

    # The memoryless table: (a).
    out.append(r"\newcommand{\tparityMemorylessTable}{" + "\n")
    out.append(r"\begin{tabular}{@{}lrrrrr@{}}" + "\n")
    out.append(r"\toprule case & $A$ & total & linear & nonlinear & static vs truth (of peak) \\ \midrule" + "\n")
    for name in ("a-tanh", "a-tanh-plan", "a-hardclip", "a-asym", "a-param"):
        case, swift, _ = results[name]
        r = reports[name]
        d = P.parse(swift)
        out.append(f"{tex_escape(name)} & {num(d.value('stimulus', 'amplitude'))} & {num(d.value('figure', 'hyst'), 3)} & {num(d.value('figure', 'linear'), 3)} & {num(r.nonlinear, 3)} & {num(r.raw_static_truth, 3)} \\\\\n")
    out.append(r"\bottomrule" + "\n" + r"\end{tabular}" + "\n}\n")

    # The paired table: (d)–(g).
    out.append(r"\newcommand{\tparityPairedTable}{" + "\n")
    out.append(r"\begin{tabular}{@{}llrrrrrrr@{}}" + "\n")
    out.append(r"\toprule case & class & voted & support & residual & $\Delta l$ & comp.\ lin. & comp.\ nonlin. & comp.\ vs truth \\" + "\n")
    out.append(r" & & & (Hz) & (rad) & (samples) & & & (of peak) \\ \midrule" + "\n")
    for name in ("d-tanh-lp", "d-tanh-hp", "e-tanh-prehp", "f-asym-hp", "g-tanh-inv-lp", "g-tanh-shift", "g-tanh-paired"):
        r = reports[name]
        cls = {"compensated": "compensated", "negligible_raw_loop": "negligible loop"}.get(r.figure_class, tex_escape(r.figure_class.replace("_", " ")))
        comp_lin = num(r.comp_linear, 2) if math.isfinite(r.comp_linear) else "--"
        comp_nl = num(r.comp_nonlinear, 2) if math.isfinite(r.comp_nonlinear) else "--"
        comp_t = num(r.comp_static_truth, 2) if r.has_compensated else "--"
        out.append(f"{tex_escape(name)} & {cls} & {r.voting} & {num(r.support_hz, 4)} & {num(r.residual_rms, 3)} & {num(r.frame_shift, 3)} & {comp_lin} & {comp_nl} & {comp_t} \\\\\n")
    out.append(r"\bottomrule" + "\n" + r"\end{tabular}" + "\n}\n")

    # Headline numbers the prose quotes.
    a6 = reports["b-lp-A6"]
    a6l = reports["b-lp-A6-15s"]
    e2 = reports["b-lp-E2"]
    e2l = reports["b-lp-E2-15s"]
    out.append(r"\newcommand{\tparityEllipseDeficitShort}{%s}" % num(100 * (1 - min(reports[n].ellipse_ratio for n in ("b-lp-E2", "b-lp-A6", "b-lp-C7", "c-delay-E2", "c-delay-A4", "c-delay-C7"))), 2) + "\n")
    out.append(r"\newcommand{\tparityEllipseDeficitLong}{%s}" % num(100 * (1 - min(reports[n].ellipse_ratio for n in ("b-lp-E2-15s", "b-lp-A6-15s", "b-lp-C7-15s"))), 2) + "\n")
    out.append(r"\newcommand{\tparityAsixRatio}{%s}" % num(a6.ellipse_ratio, 4) + "\n")
    out.append(r"\newcommand{\tparityAsixRatioLong}{%s}" % num(a6l.ellipse_ratio, 5) + "\n")
    out.append(r"\newcommand{\tparityEtwoRatio}{%s}" % num(e2.ellipse_ratio, 4) + "\n")
    out.append(r"\newcommand{\tparityEtwoRatioLong}{%s}" % num(e2l.ellipse_ratio, 5) + "\n")
    out.append(r"\newcommand{\tparityWorstFrameShift}{%s}" % num(max(abs(reports[n].frame_shift - reports[n].expected_shift) for n in ("d-tanh-lp", "d-tanh-hp", "e-tanh-prehp", "f-asym-hp", "g-tanh-inv-lp")), 2) + "\n")
    out.append(r"\newcommand{\tparityWorstResidual}{%s}" % num(max(reports[n].residual_rms for n in ("d-tanh-lp", "d-tanh-hp", "e-tanh-prehp", "f-asym-hp", "g-tanh-inv-lp")), 3) + "\n")
    out.append(r"\newcommand{\tparityWorstCompStatic}{%s}" % num(max(reports[n].comp_static_truth for n in ("d-tanh-lp", "d-tanh-hp", "e-tanh-prehp", "f-asym-hp", "g-tanh-inv-lp")), 2) + "\n")
    out.append(r"\newcommand{\tparityWorstCompArea}{%s}" % num(max(max(reports[n].comp_linear, reports[n].comp_nonlinear) for n in ("d-tanh-lp", "d-tanh-hp", "e-tanh-prehp", "f-asym-hp", "g-tanh-inv-lp")), 2) + "\n")
    out.append(r"\newcommand{\tparityWorstMemorylessNonlinear}{%s}" % num(max(reports[n].nonlinear for n in ("a-tanh", "a-hardclip", "a-asym", "a-param")), 2) + "\n")
    out.append(r"\newcommand{\tparityHardclipStatic}{%s}" % num(reports["a-hardclip"].raw_static_truth, 2) + "\n")
    out.append(r"\newcommand{\tparityTanhStatic}{%s}" % num(reports["a-tanh"].raw_static_truth, 2) + "\n")
    out.append(r"\newcommand{\tparityTanhPlanStatic}{%s}" % num(reports["a-tanh-plan"].raw_static_truth, 2) + "\n")
    out.append(r"\newcommand{\tparityTanhPlanNonlinear}{%s}" % num(reports["a-tanh-plan"].nonlinear, 2) + "\n")
    out.append(r"\newcommand{\tparityPrehpRawNonlinear}{%s}" % num(reports["e-tanh-prehp"].nonlinear, 3) + "\n")
    out.append(r"\newcommand{\tparityPrehpCompNonlinear}{%s}" % num(reports["e-tanh-prehp"].comp_nonlinear, 2) + "\n")
    out.append(r"\newcommand{\tparityAsymRawNonlinear}{%s}" % num(reports["f-asym-hp"].nonlinear, 3) + "\n")
    out.append(r"\newcommand{\tparityAsymVoted}{%d}" % reports["f-asym-hp"].voting + "\n")
    out.append(r"\newcommand{\tparityTanhVoted}{%d}" % reports["d-tanh-lp"].voting + "\n")
    d = P.parse(results["g-tanh-shift"][1])
    out.append(r"\newcommand{\tparityShiftPsi}{%s}" % num(d.value("orientation", "psi1"), 4) + "\n")
    out.append(r"\newcommand{\tparityShiftLatticeDistance}{%s}" % num(d.value("orientation", "lattice_distance"), 2) + "\n")
    # The removal parity is ESTABLISHED (Part B) — this sentence is
    # generated from the run, never typed: it changes to the stop-rule
    # wording if any paired case ever fails to compensate.
    paired_ok = all(reports[n].figure_class == "compensated" for n in ("d-tanh-lp", "d-tanh-hp", "e-tanh-prehp", "f-asym-hp", "g-tanh-inv-lp"))
    sentence = ("The removal's parity is established: every paired filtered case compensates on both sides and the two implementations agree on the compensated figure to the Swift-vs-Python tolerance."
                if paired_ok else
                "The removal's parity is NOT yet established: at least one paired case did not compensate on this run; the cases are marked expected-failure in the test and the follow-up issue is named in the handoff.")
    out.append(r"\newcommand{\tparityRemovalStatus}{%s}" % sentence + "\n")
    write(os.path.join(GENERATED, "parity-transfer.tex"), "".join(out))


# --- The Chord IMD chapter's fragments (#306 chapter three) ------------------


def gen_parameters_imd(imd):
    pl, st, lat, wn, an, rs, co, hr, dl, pt, sy = (imd[k] for k in (
        "plan", "stimulus", "lattice", "window", "analyzer", "resolution", "coherence", "harmonicRoles",
        "driveLevel", "pitch", "synthesis"))
    g96 = next(s for s in lat["snaps"] if s["sampleRateHz"] == 96000 and s["fftLength"] == pl["standardFFTLength"])["spacing"]
    g88 = next(s for s in lat["snaps"] if s["sampleRateHz"] == 88200)["spacing"]
    rows = [
        ("Plan", None),
        (r"default interval", tex_escape(pl["defaultNote1"]) + " + " + tex_escape(pl["defaultNote2"])),
        (r"default combined peak $A$ (re full scale)", num(pl["defaultPeakAmplitude"]) + f" ({num(pl['defaultPeakDBFS'], 4)} dBFS; each tone $A/2$)"),
        (r"standard rate / supported rates", num(pl["standardSampleRateHz"]) + " Hz / " + ", ".join(num(r) for r in pl["supportedSampleRatesHz"]) + " Hz"),
        (r"standard analysis length (the ceiling) $N$", num(pl["standardFFTLength"]) + f" ($2^{{{int(math.log2(pl['standardFFTLength']))}}}$)"),
        (r"minimum analysis length", num(pl["minimumFFTLength"])),
        (r"fade-in and fade-out $t_{\mathrm{fade}}$", num(st["fadeS"]) + " s"),
        (r"settle $t_{\mathrm{settle}}$", num(wn["settleS"]) + " s"),
        ("The lattice search", None),
        (r"tone cents budget", r"$\pm$" + num(lat["toneCentsBudget"]) + " cents"),
        (r"resolvable spacing bar (g $\ge$)", num(lat["resolvableSpacingBins"]) + " bins"),
        (r"enumeration ceiling (max order $K$)", num(lat["maxOrder"])),
        (r"minimum reduced sum $a + b$ at $K$", num(lat["minimumReducedSum"])),
        (r"delivered-lattice denominator limit", num(lat["maximumDeliveredDenominator"])),
        (r"standard ratio $a : b$ (the fifth)", f"{num(lat['standardRatioA'])} : {num(lat['standardRatioB'])} = {num(lat['standardIntervalCents'], 6)} cents (requested {num(lat['requestedIntervalCents'], 4)}; {num(lat['standardSurvivorCount'])} ratios survived; runner-up {num(lat['runnerUpA'])} : {num(lat['runnerUpB'])} at {num(lat['runnerUpIntervalCents'], 6)})"),
        ("The analyzer", None),
        (r"enumerated recipes (orders 2--$K$)", num(an["recipeCount"])),
        (r"local floor: inner offset / span / minimum offsets", f"{num(an['localFloorInnerOffsetBins'])} bins / $\\pm${num(an['localFloorSpanHz'], 4)} Hz / {num(an['localFloorMinimumOffsets'])} per side"),
        (r"local floor: outer offset at 2$^{21}$ (96 kHz) / 2$^{17}$", f"{num(pl['standardGrids'][3]['localFloorOuterOffsetBins'])} / {num(pl['fallbackGrids'][0]['localFloorOuterOffsetBins'])} bins"),
        (r"presence gate", r"amplitude $> 4\times$ the local floor (" + num(an["aboveFloorDB"], 4) + " dB, a literal)"),
        (r"enumeration ceiling in frequency", r"$0.95\, f_s/2$ (a literal)"),
        ("The read-time predicate", None),
        (r"local floor separation", num(rs["localFloorSeparationDB"], 4) + " dB"),
        (r"minimum floor samples", num(rs["minimumFloorSamples"])),
        (r"fade-contaminated separation bound", num(rs["fadeContaminatedSeparationDB"]) + " dB"),
        (r"played-tone / DC neighbourhood", num(rs["playedToneNeighbourhoodBins"]) + " bins"),
        (r"skirt depth $20\log_{10}(\pi g)$ at $g = $ " + f"{g96} / {g88}", f"{num(rs['skirtDepthDBAtStandardSpacing'][str(g96)], 4)} / {num(rs['skirtDepthDBAtStandardSpacing'][str(g88)], 4)} dB"),
        (r"partner-check tolerance", num(rs["partnerToleranceDB"]) + " dB"),
        ("The coherence check", None),
        (r"minimum clearance (the inner edge)", num(co["minimumClearanceBins"]) + " bins"),
        (r"detector offsets", r"$\pm 1 \ldots \pm$" + num(co["maximumDetectorOffsetBins"]) + " bins (derived: 13 $-$ 1 $-$ 3)"),
        (r"bar over the local floor", num(co["thresholdOverFloorDB"]) + " dB"),
        (r"product skirt margin", num(co["productSkirtMarginDB"]) + " dB"),
        (r"per-offset ceilings at $g = $ " + str(g96) + " (dBc)", ", ".join(num(c, 3) for c in co["productCeilingsDBcAtStandardSpacing"])),
        (r"expected noise excess, 4 / 36 bins", f"{num(co['expectedNoiseExcessDB']['4'], 3)} / {num(co['expectedNoiseExcessDB']['36'], 3)} dB"),
        ("The harmonic roles", None),
        (r"pitch tolerance", num(hr["pitchToleranceCents"]) + " cents"),
        (r"added-colour semitone classes", ", ".join(num(c) for c in hr["addedColourSemitoneClasses"])),
        (r"just-ratio search limit", num(hr["justRatioSearchLimit"]) + r" (denominator; numerator to $16\times$)"),
        ("Drive level and pitch", None),
        (r"volts label digits", num(dl["significantDigits"])),
        (r"pitch reference", "A4 = 440 Hz, 12-TET (a literal)"),
        (r"audible band", num(imd["audibleBand"]["lowHz"]) + " Hz -- " + num(imd["audibleBand"]["highHz"]) + " Hz"),
        (r"Oracle (\texttt{analysisdump imd-synth})", None),
        (r"torus quadrature points per axis", num(sy["quadraturePoints"])),
    ]
    out = ["% GENERATED by gen_docs.py from generated/manifest.json — do not edit\n",
           r"\begin{longtable}{@{}p{0.5\linewidth}p{0.45\linewidth}@{}}" + "\n",
           r"\toprule Parameter & Value \\ \midrule \endhead" + "\n"]
    for label, value in rows:
        if value is None:
            out.append(r"\multicolumn{2}{@{}l}{\textbf{%s}} \\" % label + "\n")
        else:
            out.append(f"{label} & {value} \\\\\n")
    out.append(r"\bottomrule" + "\n" + r"\end{longtable}" + "\n")
    write(os.path.join(GENERATED, "parameters-imd.tex"), "".join(out))


def gen_lattice_imd(imd):
    pl, lat, hr = imd["plan"], imd["lattice"], imd["harmonicRoles"]
    out = ["% GENERATED by gen_docs.py from generated/manifest.json — do not edit\n"]
    out.append(r"\newcommand{\imdSnapTable}{" + "\n")
    out.append(r"\begin{tabular}{@{}lrrlrrrrr@{}}" + "\n")
    out.append(r"\toprule probe & $f_s$ (Hz) & $N$ & tier & $k_1$ : $k_2$ & $g$ & $a$ : $b$ & cents & candidates \\ \midrule" + "\n")
    for s in lat["snaps"]:
        label = tex_escape(s["label"])
        tier = tex_escape(s["tier"].replace("_", " "))
        out.append(f"{label} & {num(s['sampleRateHz'])} & $2^{{{int(math.log2(s['fftLength']))}}}$ & {tier} & {num(s['binIndex1'])} : {num(s['binIndex2'])} & {num(s['spacing'])} & {num(s['reducedA'])} : {num(s['reducedB'])} & {num(s['cents1'], 3)} / {num(s['cents2'], 3)} & {num(s['resolvableCount'])} / {num(s['nonDegenerateCount'])} \\\\\n")
    out.append(r"\bottomrule" + "\n" + r"\end{tabular}" + "\n}\n")
    out.append(r"\newcommand{\imdWindowTable}{" + "\n")
    out.append(r"\begin{tabular}{@{}lrrrrrrr@{}}" + "\n")
    out.append(r"\toprule grid & $f_s$ (Hz) & $N$ & bin (Hz) & stimulus (s) & start & steady end & overrun \\ \midrule" + "\n")
    for g in pl["standardGrids"] + pl["fallbackGrids"]:
        out.append(f"{tex_escape(g['label'])} & {num(g['sampleRateHz'])} & $2^{{{int(math.log2(g['fftLength']))}}}$ & {num(g['binWidthHz'], 5)} & {num(g['stimulusDurationS'], 6)} & {num(g['windowStart'])} & {num(g['steadyEnd'])} & {num(g['fadeOverrun'])} \\\\\n")
    out.append(r"\bottomrule" + "\n" + r"\end{tabular}" + "\n}\n")
    table = hr["tables"][0]
    out.append(r"\newcommand{\imdRoleTable}{" + "\n")
    out.append(r"\begin{tabular}{@{}rrlrrl@{}}" + "\n")
    out.append(r"\toprule $k$ & Hz & pitch & cents & class & role \\ \midrule" + "\n")
    for p in table["points"]:
        role = {"thickening": "Thickening", "subOctave": "Growl (sub-octave)", "addedColour": "Added colour", "clash": "Sourness (clash)"}.get(p["role"], "--")
        cls = "--" if p["semitoneClass"] is None else num(p["semitoneClass"])
        out.append(f"{num(p['index'])} & {num(p['frequencyHz'], 5)} & {tex_escape(p['pitchName'])} & {num(p['centsFromPitch'], 3)} & {cls} & {role} \\\\\n")
    out.append(r"\bottomrule" + "\n" + r"\end{tabular}" + "\n}\n")
    out.append(r"\newcommand{\imdRoleGridHz}{%s}" % num(table["gridHz"]) + "\n")
    out.append(r"\newcommand{\imdRoleRatio}{%s : %s}" % (num(table["ratioA"]), num(table["ratioB"])) + "\n")
    third = hr["tables"][1]
    out.append(r"\newcommand{\imdThirdRatio}{%s : %s}" % (num(third["ratioA"]), num(third["ratioB"])) + "\n")
    out.append(r"\newcommand{\imdThirdGridHz}{%s}" % num(third["gridHz"]) + "\n")
    write(os.path.join(GENERATED, "lattice-imd.tex"), "".join(out))


def gen_parity_imd(m):
    import parity_imd as P
    tool = P.build_tool()
    results = P.run_all(tool, m)
    reports = {name: P.compare(case, swift, python) for name, (case, swift, python) in results.items()}
    out = ["% GENERATED by gen_docs.py from a parity run (Swift vs Python vs torus-quadrature truth) — do not edit\n"]
    out.append(r"\newcommand{\iparitySwift}{%s}" % num(P.T_SWIFT_DB, 3) + "\n")
    out.append(r"\newcommand{\iparitySwiftFiltered}{%s}" % num(P.T_SWIFT_DB_FILTERED, 3) + "\n")
    out.append(r"\newcommand{\iparityTruthRelative}{%s}" % num(P.T_SWIFT_TRUTH_RELATIVE, 3) + "\n")
    out.append(r"\newcommand{\iparityClosedForm}{%s}" % num(P.T_CLOSED_FORM_RELATIVE, 3) + "\n")
    out.append(r"\newcommand{\iparityEmptyDepth}{%s}" % num(P.EMPTY_DEPTH_DBC, 3) + "\n")
    out.append(r"\newcommand{\iparityTruthBandlimited}{%s}" % num(P.T_TRUTH_BANDLIMITED_DB, 3) + "\n")
    out.append(r"\newcommand{\iparityTruthKinked}{%s}" % num(P.T_TRUTH_KINKED_DB, 3) + "\n")
    out.append(r"\newcommand{\iparityTruthPhantom}{%s}" % num(P.T_TRUTH_PHANTOM_DB, 3) + "\n")
    out.append(r"\newcommand{\iparityFloor}{%s}" % num(P.T_FLOOR_VS_EXPECTED_DB, 3) + "\n")
    out.append(r"\newcommand{\iparityCoherenceNoise}{%s}" % num(P.T_COHERENCE_EXCESS_VS_NOISE_DB, 3) + "\n")
    out.append(r"\newcommand{\iparityCaseCount}{%d}" % len(P.CASES) + "\n")
    out.append(r"\newcommand{\iparityTwinCount}{%d}" % sum(1 for c in P.CASES if c.kind in ("device", "kinked")) + "\n")
    unfiltered = [r for r in reports.values() if not r.case.filtered]
    filtered = [r for r in reports.values() if r.case.filtered]
    out.append(r"\newcommand{\iparityWorstSwift}{%s}" % num(max(max(r.swift_header_db, r.swift_row_db) for r in unfiltered), 2) + "\n")
    out.append(r"\newcommand{\iparityWorstSwiftFiltered}{%s}" % num(max(max(r.swift_header_db, r.swift_row_db) for r in filtered), 2) + "\n")
    out.append(r"\newcommand{\iparityWorstTruthRelative}{%s}" % num(max(r.swift_truth_relative for r in reports.values()), 2) + "\n")
    out.append(r"\newcommand{\iparityWorstClosedForm}{%s}" % num(max(r.closed_form_relative for r in reports.values()), 2) + "\n")
    out.append(r"\newcommand{\iparityWorstEmpty}{%s}" % num(max(r.empty_worst_dbc for r in reports.values() if math.isfinite(r.empty_worst_dbc)), 4) + "\n")

    # The lattice table: what the shipped search chose on every grid, the
    # oracle and the Python agreeing (the test pins it against the manifest).
    out.append(r"\newcommand{\iparityLatticeTable}{" + "\n")
    out.append(r"\begin{tabular}{@{}lrrlrrrrr@{}}" + "\n")
    out.append(r"\toprule case & $f_s$ & $N$ & tier & $k_1$ : $k_2$ & $g$ & $a$ : $b$ & interval (¢) & tones (¢) \\ \midrule" + "\n")
    for name, r in reports.items():
        if r.case.kind not in ("lattice", "refusal"):
            continue
        lat = r.swift.header["lattice"]
        fs = r.swift.header["tones"]["fs"] if "tones" in r.swift.header else r.swift.header["plan"]["fs"]
        n = r.swift.header["tones"]["fft_length"] if "tones" in r.swift.header else r.swift.header["plan"]["intended_length"]
        tier = tex_escape(lat["tier"].replace("_", " "))
        out.append(f"{tex_escape(name)} & {num(float(fs))} & $2^{{{int(math.log2(float(n)))}}}$ & {tier} & {lat['bin1']} : {lat['bin2']} & {lat['g']} & {lat['a']} : {lat['b']} & {num(float(lat['interval_cents']), 5)} & {num(float(lat['cents1']), 3)} / {num(float(lat['cents2']), 3)} \\\\\n")
    out.append(r"\bottomrule" + "\n" + r"\end{tabular}" + "\n}\n")

    # The device table: each device beside its alias-free twin.
    out.append(r"\newcommand{\iparityDeviceTable}{" + "\n")
    out.append(r"\begin{tabular}{@{}lrrrrrrl@{}}" + "\n")
    out.append(r"\toprule case & content & present & S$-$P (dB) & floor (dBc) & vs truth (dB) & residue (dB) & at \\ \midrule" + "\n")
    for name, r in reports.items():
        if r.case.kind not in ("device", "kinked", "phantom"):
            continue
        v = r.swift.header.get("shipped verdict", {})
        floor = v.get("floor_dbc", "nan")
        out.append(f"{tex_escape(name)} & {r.content_count} & {v.get('present', '--')} & {num(max(r.swift_header_db, r.swift_row_db), 2)} & {num(float(floor), 5) if floor != 'nan' else '--'} & {num(r.truth_error_db, 3)} & {num(max(r.truth_residue_db, 0.0), 2)} & {tex_escape(r.truth_error_label)} \\\\\n")
    out.append(r"\bottomrule" + "\n" + r"\end{tabular}" + "\n}\n")

    # The noise table.
    out.append(r"\newcommand{\iparityNoiseTable}{" + "\n")
    out.append(r"\begin{tabular}{@{}lrrrrrrr@{}}" + "\n")
    out.append(r"\toprule case & $N$ & noise (dBFS) & median (dBc) & floor (dBc) & bins & per-bin $-$ broadband (dB) & excess (dB) \\ \midrule" + "\n")
    for name, r in reports.items():
        if r.case.kind != "noise":
            continue
        h = r.swift.header
        out.append(f"{tex_escape(name)} & $2^{{{int(math.log2(float(h['tones']['fft_length'])))}}}$ & {h['noise']['rms_dbfs']} & {num(float(h['noise']['expected_median_dbc']), 5)} & {num(float(h['shipped verdict']['floor_dbc']), 5)} & {h['shipped verdict']['floor_samples']} & {num(float(h['noise']['per_bin_below_broadband_db']), 4)} & {num(float(h['coherence (IMDAnalysis.coherenceReading)']['excess_over_floor_db']), 3)} \\\\\n")
    out.append(r"\bottomrule" + "\n" + r"\end{tabular}" + "\n}\n")

    # The predicate table: the corpus lattice, the wander, the loud device.
    out.append(r"\newcommand{\iparityPredicateTable}{" + "\n")
    out.append(r"\begin{tabular}{@{}lrrrrlrl@{}}" + "\n")
    out.append(r"\toprule case & present & absent & refused & floor bins & coherence source & excess / bar (dB) & readable \\ \midrule" + "\n")
    for name, r in reports.items():
        if r.case.kind not in ("corpus", "wander", "loud"):
            continue
        h = r.swift.header
        v = h["shipped verdict"]
        c = h["coherence (IMDAnalysis.coherenceReading)"]
        out.append(f"{tex_escape(name)} & {v['present']} & {v['absent']} & {int(v['unresolved']) + int(v['out_of_band'])} & {v['floor_samples']} & {tex_escape(c['source'].replace('_', ' '))} & {num(float(c['excess_over_floor_db']), 3)} / {num(float(c['bar_over_floor_db']))} & {tex_escape(c['readable_offsets'])} \\\\\n")
    out.append(r"\bottomrule" + "\n" + r"\end{tabular}" + "\n}\n")

    # Headline numbers the prose quotes.
    worked = reports[P.WORKED]
    ws = worked.swift
    v = ws.header["shipped verdict"]
    c = ws.header["coherence (IMDAnalysis.coherenceReading)"]
    out.append(r"\newcommand{\iparityWorkedPresent}{%s}" % v["present"] + "\n")
    out.append(r"\newcommand{\iparityWorkedAbsent}{%s}" % v["absent"] + "\n")
    out.append(r"\newcommand{\iparityWorkedFloor}{%s}" % num(float(v["floor_dbc"]), 4) + "\n")
    out.append(r"\newcommand{\iparityWorkedFloorBins}{%s}" % v["floor_samples"] + "\n")
    out.append(r"\newcommand{\iparityWorkedContent}{%d}" % worked.content_count + "\n")
    out.append(r"\newcommand{\iparityWorkedTruthError}{%s}" % num(worked.truth_error_db, 2) + "\n")
    out.append(r"\newcommand{\iparityWorkedTruthErrorAt}{%s}" % tex_escape(worked.truth_error_label) + "\n")
    out.append(r"\newcommand{\iparityWorkedResidue}{%s}" % num(max(worked.truth_residue_db, 0.0), 2) + "\n")
    out.append(r"\newcommand{\iparityWorkedCoherenceExcess}{%s}" % num(float(c["excess_over_floor_db"]), 3) + "\n")
    out.append(r"\newcommand{\iparityWorkedLoudest}{%s}" % num(float(c["loudest_product_dbc"]), 4) + "\n")
    def level(rows, m_, n_):
        row = next(r for r in rows if int(r["m"]) == m_ and int(r["n"]) == n_)
        return row
    for macro, (m_, n_) in (("TwoFOneMinusFTwo", (2, -1)), ("TwoFTwoMinusFOne", (-1, 2)), ("ThreeFOne", (3, 0)), ("FOnePlusFTwo", (1, 1))):
        row = level(ws.rows, m_, n_)
        out.append(r"\newcommand{\iparityWorked%sLevel}{%s}" % (macro, num(row["level_dbc"], 5)) + "\n")
        out.append(r"\newcommand{\iparityWorked%sTruth}{%s}" % (macro, num(row["truth_dbc"], 5)) + "\n")
        out.append(r"\newcommand{\iparityWorked%sReading}{%s}" % (macro, tex_escape(row["reading"])) + "\n")
    hard = reports["c-hardclip"]
    out.append(r"\newcommand{\iparityHardclipAlias}{%s}" % num(hard.truth_error_db, 3) + "\n")
    out.append(r"\newcommand{\iparityHardclipAliasAt}{%s}" % tex_escape(hard.truth_error_label) + "\n")
    asym = reports["b-asym"]
    out.append(r"\newcommand{\iparityAsymAlias}{%s}" % num(asym.truth_error_db, 3) + "\n")
    out.append(r"\newcommand{\iparityAsymAliasAt}{%s}" % tex_escape(asym.truth_error_label) + "\n")
    out.append(r"\newcommand{\iparityAsymTwin}{%s}" % num(reports["b-asym-twin"].truth_error_db, 2) + "\n")
    out.append(r"\newcommand{\iparityHardclipTwin}{%s}" % num(reports["c-hardclip-twin"].truth_error_db, 2) + "\n")
    out.append(r"\newcommand{\iparityTanhTwin}{%s}" % num(reports["c-tanh-twin"].truth_error_db, 2) + "\n")
    out.append(r"\newcommand{\iparityWorstBandlimitedResidue}{%s}" % num(max(reports[n].truth_residue_db for n in ("b-poly", "b-squarer", "c-tanh", "f-squarer-hp", "f-squarer-lp", "f-tanh-prehp", "j-latency")), 2) + "\n")
    out.append(r"\newcommand{\iparityPhantomWorst}{%s}" % num(reports["d-phantom"].truth_error_db, 2) + "\n")
    phantom = reports["d-phantom"].swift.header["shipped verdict"]
    out.append(r"\newcommand{\iparityPhantomPresent}{%s}" % phantom["present"] + "\n")
    out.append(r"\newcommand{\iparityPhantomOutOfBand}{%s}" % phantom["out_of_band"] + "\n")
    # The latency shift: the worked example 100 samples late against itself,
    # the worst content-product move and the tolerance it is held to.
    zero = {(int(r["m"]), int(r["n"])): r for r in reports["c-tanh"].swift.rows}
    shifts = [abs(r["level_dbc"] - zero[(int(r["m"]), int(r["n"]))]["level_dbc"])
              for r in reports["j-latency"].swift.rows
              if math.isfinite(r["truth_dbc"]) and r["truth_dbc"] > -120]
    out.append(r"\newcommand{\iparityLatencyTolerance}{%s}" % num(P.T_LATENCY_SHIFT_DB, 3) + "\n")
    out.append(r"\newcommand{\iparityWorstLatencyShift}{%s}" % num(max(shifts), 2) + "\n")
    out.append(r"\newcommand{\iparityLatencySamples}{%d}" % (int(reports["j-latency"].swift.header["window"]["start"]) - int(reports["c-tanh"].swift.header["window"]["start"])) + "\n")
    long_ = reports["e-identity-80"].swift.header
    short = reports["e-identity-corpus-80"].swift.header
    out.append(r"\newcommand{\iparityPerBinLong}{%s}" % num(float(long_["noise"]["per_bin_below_broadband_db"]), 4) + "\n")
    out.append(r"\newcommand{\iparityPerBinShort}{%s}" % num(float(short["noise"]["per_bin_below_broadband_db"]), 4) + "\n")
    out.append(r"\newcommand{\iparityFloorLongDeficit}{%s}" % num(abs(float(long_["shipped verdict"]["floor_dbc"]) - float(long_["noise"]["expected_median_dbc"])), 2) + "\n")
    out.append(r"\newcommand{\iparityFloorShortDeficit}{%s}" % num(abs(float(short["shipped verdict"]["floor_dbc"]) - float(short["noise"]["expected_median_dbc"])), 2) + "\n")
    out.append(r"\newcommand{\iparityCleanExcess}{%s}" % num(float(long_["coherence (IMDAnalysis.coherenceReading)"]["excess_over_floor_db"]), 3) + "\n")
    out.append(r"\newcommand{\iparityCleanExpected}{%s}" % num(float(long_["coherence (IMDAnalysis.coherenceReading)"]["expected_noise_excess_db"]), 3) + "\n")
    legacy = reports["h-wander-legacy"].swift.header["coherence (IMDAnalysis.coherenceReading)"]
    shipped = reports["h-wander-shipped"].swift.header["coherence (IMDAnalysis.coherenceReading)"]
    out.append(r"\newcommand{\iparityWanderLegacyWorst}{%s}" % num(float(legacy["worst_dbc"]), 4) + "\n")
    out.append(r"\newcommand{\iparityWanderLegacyExcess}{%s}" % num(float(legacy["excess_over_floor_db"]), 3) + "\n")
    out.append(r"\newcommand{\iparityWanderLegacyPairDifference}{%s}" % num(float(legacy["pair_difference_db"]), 3) + "\n")
    out.append(r"\newcommand{\iparityWanderExpectedDifference}{%s}" % num(float(legacy["expected_difference_db"]), 3) + "\n")
    out.append(r"\newcommand{\iparityWanderShippedWorst}{%s}" % num(float(shipped["worst_dbc"]), 4) + "\n")
    out.append(r"\newcommand{\iparityWanderShippedExcess}{%s}" % num(float(shipped["excess_over_floor_db"]), 3) + "\n")
    out.append(r"\newcommand{\iparityWanderShippedPairDifference}{%s}" % num(float(shipped["pair_difference_db"]), 3) + "\n")
    loud = reports["i-loud-squarer"].swift.header
    out.append(r"\newcommand{\iparityLoudLoudest}{%s}" % num(float(loud["coherence (IMDAnalysis.coherenceReading)"]["loudest_product_dbc"]), 4) + "\n")
    out.append(r"\newcommand{\iparityLoudUnderSkirt}{%s}" % loud["loudest skirt"]["under_skirt"] + "\n")
    out.append(r"\newcommand{\iparityLoudSkirt}{%s}" % num(float(loud["loudest skirt"]["skirt_db"]), 3) + "\n")
    corpus = reports["g-corpus-squarer"].swift
    near = sum(1 for r in corpus.rows if r["reading"] == "near_played_tone")
    neighbour = sum(1 for r in corpus.rows if r["reading"] == "near_louder_product")
    out.append(r"\newcommand{\iparityCorpusNearNote}{%d}" % near + "\n")
    out.append(r"\newcommand{\iparityCorpusNeighbour}{%d}" % neighbour + "\n")
    out.append(r"\newcommand{\iparityCorpusFloorBins}{%s}" % corpus.header["shipped verdict"]["floor_samples"] + "\n")
    # Part B's status is GENERATED from the run, never typed: every
    # predicate case (the corpus lattice, the wander, the loud device)
    # reads identically on both sides, or the stop-rule wording appears.
    part_b = [reports[n] for n in ("g-corpus-squarer", "g-corpus-cubic", "h-wander-legacy", "h-wander-shipped", "i-loud-squarer")]
    ok = all(not (r.discrete_mismatches or r.text_mismatches or r.header_field_mismatches) for r in part_b)
    sentence = ("Part B's parity is established: on every predicate case — the corpus lattice's refusals by position and beside a louder product, the wander fixture through the legacy path and through the detector, and the device whose products stand above its tones — the two implementations agree on every reading, every count and both registers' sentences."
                if ok else
                "Part B's parity is NOT yet established: at least one predicate case reads differently on the two sides on this run; the cases are marked expected-failure in the test and the follow-up issue is named in the handoff.")
    out.append(r"\newcommand{\iparityPartBStatus}{%s}" % sentence + "\n")
    write(os.path.join(GENERATED, "parity-imd.tex"), "".join(out))



# --- The Gain Map chapter's fragments (#306 chapter four) --------------------


def _rule_number(rule: str, pattern: str) -> str:
    """A literal the manifest carries only inside a rule string, read from
    there (the HD writer's minimum-half-width precedent)."""
    m = re.search(pattern, rule)
    assert m, f"rule string lacks {pattern!r}: {rule[:80]}"
    return m.group(1).replace("\u2212", "-")


def gen_parameters_journey(gmap):
    pr, pl, su, ma, fl, pk, cl, sy = (gmap[k] for k in (
        "probe", "plan", "summary", "masks", "floor", "peak", "cleanup", "synthesis"))
    residue_drive = _rule_number(fl["residueRule"], r"at ([\u2212-]?\d+(?:\.\d+)?) dBFS")
    summaries_hz = _rule_number(cl["summariesRule"], r"nearest (\d+(?:\.\d+)?) Hz")
    summaries_confidence = _rule_number(cl["summariesRule"], r"confidence ([0-9.]+)")
    guard = _rule_number(cl["readingRule"], r"max\(thd_i \u2212 thd_\{i\u22121\}, ([0-9e\u2212-]+)\)")
    rows = [
        ("Drive windows", None),
        (r"hardware window (floor / ceiling / levels)", f"{num(pr['floorDBFS'])} / {num(pr['ceilingDBFS'])} dBFS / {num(pr['defaultLevels'])}"),
        (r"plugin window (floor / ceiling / levels)", f"{num(pr['pluginFloorDBFS'])} / {num(pr['pluginCeilingDBFS'])} dBFS / {num(pr['defaultLevels'])}"),
        (r"hardware lattice step", num((pr["ceilingDBFS"] - pr["floorDBFS"]) / (pr["defaultLevels"] - 1), 4) + " dB"),
        ("Plan", None),
        (r"sweep band $f_1$ -- $f_2$", num(pl["startHz"]) + " Hz -- " + num(pl["endHz"]) + " Hz"),
        (r"sweep length (default) / offered", num(pl["sweepDurationS"]) + " s / " + ", ".join(num(x) for x in pl["sweepDurationChoicesS"]) + " s (not stored)"),
        (r"actual duration / rate constant $L$ at the default", num(pl["actualDurationS"], 6) + " s / " + num(pl["rateConstantS"]) + " s"),
        (r"pre-roll / tail silence", num(pl["prerollS"]) + " s / " + num(pl["tailS"]) + " s"),
        (r"sample rate $f_s$ (the manifest's)", num(pl["sampleRateHz"]) + " Hz"),
        (r"sweep samples / pre-roll / tail at $f_s$", f"{num(pl['sweepSampleCount'])} / {num(pl['prerollSamples'])} / {num(pl['tailSamples'])}"),
        (r"analyzer: harmonic count $K$ / response DFT $M$ / half-width cap", f"{num(pl['harmonicCount'])} / {num(pl['responseFFTLength'])} / {num(pl['maxWindowHalfWidthS'])} s"),
        (r"export grid columns", num(pl["exportFrequencyCount"]) + f" ({num(pl['exportGridHz'][0])}--{num(pl['exportGridHz'][-1])} Hz inclusive)"),
        ("Summary", None),
        (r"integration band", num(su["band"]["lowHz"]) + " Hz -- " + num(su["band"]["highHz"]) + " Hz"),
        (r"edge mask guard ratio (a quarter tone)", num(ma["bottomEdgeGuardRatio"], 8)),
        (r"masked columns on the default grid (bottom / top / truncated)", f"{', '.join(num(c) for c in ma['bottomEdgeColumns'])} / {', '.join(num(c) for c in ma['topEdgeColumns'])} / {', '.join(num(c) for c in ma['truncatedColumns']) or 'none'}"),
        ("Floor", None),
        (r"stamp median window (the Gain Map) / per-harmonic path", num(fl["stampMedianPoints"]) + " points / 1 (verbatim)"),
        (r"calibration analyzed sweeps / level", num(fl["calibrationAnalyzedSweepCount"]) + " / " + num(fl["calibrationLevelDBFS"]) + " dBFS"),
        (r"calibration sweep (the app's)", f"{num(sy['calibrationStartHz'])} Hz to round({num(sy['calibrationEndFraction'])} $f_s$), {num(sy['calibrationDurationS'])} s, {num(sy['calibrationPrerollS'])} s before / {num(sy['calibrationTailS'])} s after"),
        (r"residue capture drive", residue_drive + " dBFS (a literal; the read is a ratio)"),
        ("Peak tile", None),
        (r"minimum margin", num(pk["minimumMarginDB"]) + " dB"),
        ("Cleanup", None),
        (r"threshold (bisected from the shipped initializer)", num(cl["threshold"]) + " (" + num(100 * cl["threshold"]) + r" \%)"),
        (r"tile column (nearest in log frequency)", num(cl["tileFrequencyHz"]) + " Hz"),
        (r"summaries' fallback: reference / minimum levels / confidence", summaries_hz + " Hz (linear nearest) / 3 / " + summaries_confidence + " (literals)"),
        (r"crossing interpolation guard", guard + " (a literal)"),
        (r"Oracle (\texttt{analysisdump journey-synth})", None),
        (r"ladder quadrature points", num(sy["quadraturePoints"])),
    ]
    out = ["% GENERATED by gen_docs.py from generated/manifest.json — do not edit\n",
           r"\begin{longtable}{@{}p{0.5\linewidth}p{0.45\linewidth}@{}}" + "\n",
           r"\toprule Parameter & Value \\ \midrule \endhead" + "\n"]
    for label, value in rows:
        if value is None:
            out.append(r"\multicolumn{2}{@{}l}{\textbf{%s}} \\" % label + "\n")
        else:
            out.append(f"{label} & {value} \\\\\n")
    out.append(r"\bottomrule" + "\n" + r"\end{longtable}" + "\n")
    write(os.path.join(GENERATED, "parameters-journey.tex"), "".join(out))


def gen_residue_journey(gmap):
    """The residue per column per length on the shipped grid, from the
    manifest (the shipped derivation RUN there), as a table and as the
    macros the prose quotes."""
    pl, fl = gmap["plan"], gmap["floor"]
    grid = pl["exportGridHz"]
    lengths = [str(int(x)) for x in pl["sweepDurationChoicesS"]]
    out = ["% GENERATED by gen_docs.py from generated/manifest.json — do not edit\n"]
    out.append(r"\newcommand{\journeyResidueTable}{" + "\n")
    out.append(r"\begin{tabular}{@{}rr" + "r" * len(lengths) + "r@{}}" + "\n")
    out.append(r"\toprule $j$ & $f_j$ (Hz) & " + " & ".join(f"{l} s" for l in lengths) + r" & worst \\ \midrule" + "\n")
    for j, f in enumerate(grid[:8]):
        cells = " & ".join(num(fl["residuePerLengthDB"][l][j], 4) for l in lengths)
        out.append(f"{j} & {num(f, 4)} & {cells} & {num(fl['residueWorstDB'][j], 4)} \\\\\n")
    out.append(r"\bottomrule" + "\n" + r"\end{tabular}" + "\n}\n")
    out.append(r"\newcommand{\journeyResidueColumnOneHz}{%s}" % num(grid[1], 4) + "\n")
    for l in lengths:
        out.append(r"\newcommand{\journeyResidueColumnOne%s}{%s}" % ({"2": "Two", "5": "Five", "10": "Ten"}[l], num(fl["residuePerLengthDB"][l][1], 4)) + "\n")
        out.append(r"\newcommand{\journeyResidueColumnTwo%s}{%s}" % ({"2": "Two", "5": "Five", "10": "Ten"}[l], num(fl["residuePerLengthDB"][l][2], 4)) + "\n")
    out.append(r"\newcommand{\journeyResidueWorstColumnOne}{%s}" % num(fl["residueWorstDB"][1], 4) + "\n")
    out.append(r"\newcommand{\journeyHardwareStep}{%s}" % num((gmap["probe"]["ceilingDBFS"] - gmap["probe"]["floorDBFS"]) / (gmap["probe"]["defaultLevels"] - 1), 4) + "\n")
    out.append(r"\newcommand{\journeyPluginStep}{%s}" % num((gmap["probe"]["pluginCeilingDBFS"] - gmap["probe"]["pluginFloorDBFS"]) / (gmap["probe"]["defaultLevels"] - 1), 4) + "\n")
    # The stamp's grid (floor.stampSourceRule): 128 log points from 1.5·f1 to
    # the calibration sweep's f2 = round(0.45·fs) — the 1.5 and the 128 are
    # the kernel's literals (rule strings); f1, 0.45 and fs are the named
    # statics the oracle exposes. ±3 points of 127 intervals over that span.
    sc = gmap["shippedConstants"]
    stamp_top_hz = round(sc["JourneySynthPlan.calibrationEndFraction"] * gmap["plan"]["sampleRateHz"])
    stamp_bottom_hz = 1.5 * sc["JourneySynthPlan.calibrationStartHz"]
    out.append(r"\newcommand{\journeyStampMedianOctaves}{%s}" % num(((fl["stampMedianPoints"] - 1) / 2) * math.log2(stamp_top_hz / stamp_bottom_hz) / 127, 2) + "\n")
    write(os.path.join(GENERATED, "residue-journey.tex"), "".join(out))


def gen_parity_journey(m):
    import parity_journey as P
    tool = P.build_tool()
    results = P.run_all(tool, m)
    leakage = P.leakage_from(results)
    reports = {name: P.compare(case, swift, python, m, leakage) for name, (case, swift, python) in results.items()}
    out = ["% GENERATED by gen_docs.py from a parity run (Swift vs Python vs the closed-form ladder) — do not edit\n"]
    for macro, value in (("SwiftTolerance", P.T_SWIFT_DB), ("SwiftFilteredTolerance", P.T_SWIFT_DB_FILTERED),
                         ("EmptyDepth", P.EMPTY_DEPTH_DB), ("TruthSmooth", P.T_TRUTH_SMOOTH_DB), ("TruthPhantom", P.T_TRUTH_PHANTOM_DB),
                         ("TruthFiltered", P.T_TRUTH_FILTERED_DB), ("THDSmooth", P.T_THD_SMOOTH_DB), ("THDFiltered", P.T_THD_FILTERED_DB),
                         ("Cleanup", P.T_CLEANUP_DB), ("ResidueVsLaw", P.T_RESIDUE_VS_LAW_DB), ("GainInvariance", P.T_GAIN_INVARIANCE_DB),
                         ("Latency", P.T_LATENCY_DB), ("CorpusPeak", P.T_CORPUS_PEAK_DB), ("CorpusBound", P.T_CORPUS_BOUND_RELATIVE)):
        out.append(r"\newcommand{\jparity%s}{%s}" % (macro, num(value, 3)) + "\n")
    out.append(r"\newcommand{\jparityCaseCount}{%d}" % len(P.CASES) + "\n")
    out.append(r"\newcommand{\jparityTwinCount}{%d}" % len(P.TWIN_OF) + "\n")
    unfiltered = [r for r in reports.values() if not r.case.filtered]
    filtered = [r for r in reports.values() if r.case.filtered]
    out.append(r"\newcommand{\jparityWorstSwift}{%s}" % num(max(max(r.swift_header_db, r.swift_row_db) for r in unfiltered), 2) + "\n")
    out.append(r"\newcommand{\jparityWorstSwiftFiltered}{%s}" % num(max(max(r.swift_header_db, r.swift_row_db) for r in filtered), 2) + "\n")
    # The leakage map: the first four unmasked-side columns per order.
    out.append(r"\newcommand{\jparityLeakageTable}{" + "\n")
    out.append(r"\begin{tabular}{@{}r" + "r" * 5 + "@{}}" + "\n")
    grid = m["gainMap"]["plan"]["exportGridHz"]
    cols = [1, 2, 3, 4, 8]
    out.append(r"\toprule $k$ & " + " & ".join("%s Hz" % num(grid[j], 4) for j in cols) + r" \\ \midrule" + "\n")
    for k in sorted(leakage):
        out.append(f"{k} & " + " & ".join(num(leakage[k][j], 4) for j in cols) + " \\\\\n")
    out.append(r"\bottomrule" + "\n" + r"\end{tabular}" + "\n}\n")
    out.append(r"\newcommand{\jparityLeakageHTwoColumnOne}{%s}" % num(leakage[2][1], 4) + "\n")
    out.append(r"\newcommand{\jparityLeakageHThreeColumnOne}{%s}" % num(leakage[3][1], 4) + "\n")
    out.append(r"\newcommand{\jparityLeakageHFiveColumnOne}{%s}" % num(leakage[5][1], 4) + "\n")
    out.append(r"\newcommand{\jparityLeakageHThreeColumnTwo}{%s}" % num(leakage[3][2], 4) + "\n")
    # The device table: every noiseless case beside its bars.
    out.append(r"\newcommand{\jparityDeviceTable}{" + "\n")
    out.append(r"\begin{tabular}{@{}lrrrrrrrr@{}}" + "\n")
    out.append(r"\toprule case & cells & S$-$P (dB) & raw (dB) & at & residue (dB) & 30 dB bar & 40 dB bar & THD residue \\ \midrule" + "\n")
    for name, r in reports.items():
        if r.content_count == 0 or r.case.kind == "linear":
            continue
        out.append(f"{tex_escape(name)} & {r.content_count} & {num(max(r.swift_header_db, r.swift_row_db), 2)} & {num(r.truth_error_db, 3)} & {tex_escape(r.truth_error_label)} & {num(max(r.truth_residue_db, 0.0), 2)} & {num(r.bar_error[30][0], 3)} & {num(r.bar_error[40][0], 3)} & {num(max(r.thd_residue_db, 0.0), 2)} \\\\\n")
    out.append(r"\bottomrule" + "\n" + r"\end{tabular}" + "\n}\n")
    # The read-time table: every noisy case's tiles on the Swift side.
    tile = "cleanup tile (nearest column to 220.0 Hz)"
    out.append(r"\newcommand{\jparityReadTimeTable}{" + "\n")
    out.append(r"\begin{tabular}{@{}llrlrrr@{}}" + "\n")
    out.append(r"\toprule case & peak tile & value (\%) & cleanup tile & level (dBFS) & absent & S$-$P (dB) \\ \midrule" + "\n")
    for name, r in reports.items():
        if not r.case.noisy:
            continue
        h = r.swift.header
        pk = h["peak tile"]
        value = pk["peak_pct"] if pk["state"] == "peak" else pk["bound_pct"]
        value = "--" if value == "nan" else num(float(value), 4)
        state = {"peak": "peak", "at_floor": "at floor ($\\le$)", "fundamental_absent": "no fundamental"}.get(pk["state"], pk["state"])
        c = h[tile]
        level = "--" if c["level_dbfs"] == "nan" else num(float(c["level_dbfs"]), 4)
        out.append(f"{tex_escape(name)} & {state} & {value} & {tex_escape(c['state'].replace('_', ' '))} & {level} & {h['fundamental verdict']['absent']} & {num(max(r.swift_header_db, r.swift_row_db), 2)} \\\\\n")
    out.append(r"\bottomrule" + "\n" + r"\end{tabular}" + "\n}\n")
    # Headline numbers the prose quotes.
    worked = reports[P.WORKED]
    ws = worked.swift
    out.append(r"\newcommand{\jparityWorkedPeak}{%s}" % num(float(ws.header["peak tile"]["peak_pct"]), 4) + "\n")
    out.append(r"\newcommand{\jparityWorkedTruthPeak}{%s}" % num(float(ws.header["truth peak tile"]["peak_pct"]), 4) + "\n")
    out.append(r"\newcommand{\jparityWorkedCleanup}{%s}" % num(float(ws.header[tile]["level_dbfs"]), 4) + "\n")
    out.append(r"\newcommand{\jparityWorkedTruthCleanup}{%s}" % num(float(ws.header["truth " + tile]["level_dbfs"]), 4) + "\n")
    out.append(r"\newcommand{\jparityWorkedCleanupColumnHz}{%s}" % num(float(ws.header[tile]["column_hz"]), 4) + "\n")
    out.append(r"\newcommand{\jparityWorkedContent}{%d}" % worked.content_count + "\n")
    out.append(r"\newcommand{\jparityWorkedRaw}{%s}" % num(worked.truth_error_db, 3) + "\n")
    out.append(r"\newcommand{\jparityWorkedRawAt}{%s}" % tex_escape(worked.truth_error_label) + "\n")
    out.append(r"\newcommand{\jparityWorkedResidue}{%s}" % num(max(worked.truth_residue_db, 0.0), 2) + "\n")
    out.append(r"\newcommand{\jparityWorkedThirty}{%s}" % num(worked.bar_error[30][0], 3) + "\n")
    out.append(r"\newcommand{\jparityWorkedForty}{%s}" % num(worked.bar_error[40][0], 3) + "\n")
    out.append(r"\newcommand{\jparityWorkedTHDResidue}{%s}" % num(max(worked.thd_residue_db, 0.0), 2) + "\n")
    out.append(r"\newcommand{\jparityWorkedCleanupError}{%s}" % num(worked.cleanup_error_db, 3) + "\n")
    out.append(r"\newcommand{\jparityBoundThirty}{%s}" % num(20 * math.log10(1 + 10 ** (-30 / 20)), 3) + "\n")
    out.append(r"\newcommand{\jparityBoundForty}{%s}" % num(20 * math.log10(1 + 10 ** (-40 / 20)), 3) + "\n")
    out.append(r"\newcommand{\jparityWorstThirty}{%s}" % num(max(r.bar_error[30][0] for r in reports.values() if r.content_count and not r.case.filtered and r.case.kind != "linear"), 3) + "\n")
    out.append(r"\newcommand{\jparityWorstForty}{%s}" % num(max(r.bar_error[40][0] for r in reports.values() if r.content_count and not r.case.filtered and r.case.kind != "linear"), 3) + "\n")
    out.append(r"\newcommand{\jparityWorstResidueSmooth}{%s}" % num(max(max(reports[n].truth_residue_db, 0.0) for n in ("a-tanh", "a-poly")), 2) + "\n")
    out.append(r"\newcommand{\jparityWorstResiduePhantom}{%s}" % num(max(max(reports[n + "-twin"].truth_residue_db, 0.0) for n in P.TWIN_OF), 2) + "\n")
    out.append(r"\newcommand{\jparityWorstResidueFiltered}{%s}" % num(max(max(r.truth_residue_db, 0.0) for r in filtered), 2) + "\n")
    out.append(r"\newcommand{\jparityWorstTHDSmooth}{%s}" % num(max(max(reports[n].thd_residue_db, 0.0) for n in ("a-tanh", "a-poly")), 2) + "\n")
    out.append(r"\newcommand{\jparityWorstTHDFiltered}{%s}" % num(max(max(r.thd_residue_db, 0.0) for r in filtered), 2) + "\n")
    out.append(r"\newcommand{\jparityWorstCleanup}{%s}" % num(max(r.cleanup_error_db for r in reports.values()), 3) + "\n")
    # The identity through noise: the residue at the first unmasked column, the law's numbers.
    b5 = reports["b-identity-5s"].python
    first = b5.lists["masks"]["bottom_edge"].index("0")
    for label, seconds in (("Two", 2), ("Five", 5), ("Ten", 10)):
        out.append(r"\newcommand{\jparityResiduePython%s}{%s}" % (label, num(float(b5.series["residue length_s=%s" % hd.fmt(float(seconds))][first]), 4)) + "\n")
        out.append(r"\newcommand{\jparityResidueLaw%s}{%s}" % (label, num(P.RESIDUE_LAW_DB[seconds], 4)) + "\n")
    bp = reports["b-identity-5s"].swift.header["peak tile"]
    out.append(r"\newcommand{\jparityIdentityBound}{%s}" % num(float(bp["bound_pct"]), 3) + "\n")
    # The gain invariance and the latency identity.
    g0, g12 = reports["e-tanh-gain0"].swift, reports["e-tanh-gain12"].swift
    out.append(r"\newcommand{\jparityGainShift}{%s}" % num(g12.rows[0]["h1_db"] - g0.rows[0]["h1_db"], 6) + "\n")
    out.append(r"\newcommand{\jparityGainMarginMove}{%s}" % num(max(P._diff(a["margin_db"], b["margin_db"]) for a, b in zip(g0.rows, g12.rows)), 2) + "\n")
    out.append(r"\newcommand{\jparityGainStamp}{%s}" % num(float(g12.header["calibration"]["chain_gain_db"]), 5) + "\n")
    zero, late = reports["a-tanh"].swift, reports["j-latency"].swift
    out.append(r"\newcommand{\jparityLatencyFound}{%s}" % late.header["calibration"]["latency_samples"] + "\n")
    out.append(r"\newcommand{\jparityLatencyMove}{%s}" % num(max(max(P._diff(a[f"h{k}_db"], b[f"h{k}_db"]) for k in zero.orders) for a, b in zip(zero.rows, late.rows)), 2) + "\n")
    # The operative floor and the absent fundamental.
    f = reports["f-operative"].swift
    out.append(r"\newcommand{\jparityOperativeAbsolute}{%s}" % num(float(f.header["precheck"]["absolute_dbfs"]), 4) + "\n")
    out.append(r"\newcommand{\jparityOperativePeak}{%s}" % num(float(f.header["peak tile"]["peak_pct"]), 4) + "\n")
    out.append(r"\newcommand{\jparityOperativeStampFloor}{%s}" % num(20 * math.log10(max(float(x.split(":")[1]) for x in f.series["stamp"].values())), 3) + "\n")
    c = reports["c-absent"].swift.header
    out.append(r"\newcommand{\jparityAbsentDepth}{%s}" % num(float(c["peak tile"]["depth_db"]), 4) + "\n")
    out.append(r"\newcommand{\jparityAbsentFraction}{%s}" % num(float(c["fundamental verdict"]["absent_fraction"]), 3) + "\n")
    g = reports["g-plugin-hardclip"].swift.header
    out.append(r"\newcommand{\jparityPluginPeak}{%s}" % num(float(g["peak tile"]["peak_pct"]), 4) + "\n")
    out.append(r"\newcommand{\jparityPluginCleanup}{%s}" % num(float(g[tile]["level_dbfs"]), 4) + "\n")
    d = reports["d-never-clean"].swift.header
    out.append(r"\newcommand{\jparityNeverCleanPeak}{%s}" % num(float(d["peak tile"]["peak_pct"]), 4) + "\n")
    # Part B on the corpus: the Python's tiles beside the kernel's.
    out.append(r"\newcommand{\jparityCorpusTable}{" + "\n")
    out.append(r"\begin{tabular}{@{}rlrr@{}}" + "\n")
    out.append(r"\toprule record & tile & Python (\%) & kernel (\%) \\ \midrule" + "\n")
    corpus_ok = True
    for r in P.corpus_records():
        reading = P.corpus_reading(r, m)
        state, value = P.CORPUS_PINNED[r.pk]
        label = "peak" if state == "peak" else "at floor ($\\le$)"
        out.append(f"{r.pk} & {label} & {num(reading.peak[1], 6)} & {num(value, 6)} \\\\\n")
        if reading.peak[0] != state:
            corpus_ok = False
        elif state == "peak" and abs(20 * math.log10(reading.peak[1] / value)) >= P.T_CORPUS_PEAK_DB:
            corpus_ok = False
        elif state != "peak" and abs(reading.peak[1] - value) > P.T_CORPUS_BOUND_RELATIVE * value:
            corpus_ok = False
    out.append(r"\bottomrule" + "\n" + r"\end{tabular}" + "\n}\n")
    # Part B's status is GENERATED from the run, never typed.
    part_b = [reports[n] for n in ("b-identity-2s", "b-identity-5s", "b-identity-10s", "c-absent", "d-never-clean",
                                   "e-tanh-gain0", "e-tanh-gain12", "f-operative", "g-plugin-hardclip")]
    ok = corpus_ok and all(not (r.discrete_mismatches or r.header_field_mismatches) and r.swift_row_db <= r.case.swift_tolerance_db for r in part_b)
    sentence = ("Part B's parity is established: on every read-time case — the identity through noise at the three sweep lengths, the device with no fundamental, the never-clean clipper, the loop 12 dB louder, the operative floor on a silent stamp, and the plugin window — the two implementations agree on every margin, every flag, every tile and every verdict, and on the corpus grids the reimplementation reproduces the kernel's own tiles to the digit."
                if ok else
                "Part B's parity is NOT yet established: at least one read-time case, or a corpus tile, reads differently on the two sides on this run; the cases are marked expected-failure in the test and the follow-up issue is named in the handoff.")
    out.append(r"\newcommand{\jparityPartBStatus}{%s}" % sentence + "\n")
    write(os.path.join(GENERATED, "parity-journey.tex"), "".join(out))

# --- Numbers in words (#307) --------------------------------------------------
# A tolerance such as 1e-10 prints as "1e-10" in lay prose because the parity
# macros are shared with the technical chapter. Beside each scalar macro the
# lay chapter quotes, a WORDS form is generated from the same value: an exact
# power of ten is named ("a ten-billionth"), anything else is stated as
# "about N × 10^k" in words ("about seven ten-trillionths"). A value the
# formatter cannot name comes back as the number itself — never a guess.

FRACTION_NAMES = {
    1: "tenth", 2: "hundredth", 3: "thousandth", 4: "ten-thousandth",
    5: "hundred-thousandth", 6: "millionth", 7: "ten-millionth",
    8: "hundred-millionth", 9: "billionth", 10: "ten-billionth",
    11: "hundred-billionth", 12: "trillionth", 13: "ten-trillionth",
    14: "hundred-trillionth", 15: "quadrillionth",
}
ONES = {1: "one", 2: "two", 3: "three", 4: "four", 5: "five", 6: "six", 7: "seven", 8: "eight", 9: "nine"}
# The three fractions English names outright; every other value goes through
# the power-of-ten rule.
NAMED_FRACTIONS = {0.5: "a half", 0.25: "a quarter", 0.75: "three quarters"}


def in_words(value, fallback: str) -> str:
    """The English name of a positive value under one, or `fallback` (the
    number as the number macro prints it) when there is no name for it."""
    try:
        v = float(value)
    except (TypeError, ValueError):
        return fallback
    if not math.isfinite(v) or not (0 < v < 1):
        return fallback
    for named, name in NAMED_FRACTIONS.items():
        if abs(v - named) <= 1e-12:
            return name
    k = -math.floor(math.log10(v))          # 10^-k <= v < 10^-(k-1)
    mantissa = round(v * 10 ** k, 1)        # two significant figures
    if mantissa >= 10:
        k -= 1
        mantissa = 1.0
    if k not in FRACTION_NAMES:
        return fallback
    name = FRACTION_NAMES[k]
    if mantissa == 1.0:
        return f"a {name}"
    if mantissa == int(mantissa):
        return f"{ONES[int(mantissa)]} {name}s"
    rounded = int(math.floor(mantissa + 0.5))   # half up, never banker's
    if rounded >= 10:
        k -= 1
        if k not in FRACTION_NAMES:
            return fallback
        return f"about a {FRACTION_NAMES[k]}"
    if rounded == 1:
        return f"about a {name}"
    return f"about {ONES[rounded]} {name}s"


SCALAR_MACRO = re.compile(r"^\\newcommand\{\\([A-Za-z]+)\}\{(-?[0-9.]+(?:e-?[0-9]+)?)\}\s*$")


def parity_words_macros(parity_file: str):
    """One `\\<name>Words` macro per single-line scalar `\\newcommand` in a
    committed (or just regenerated) parity fragment, derived from the literal
    the fragment prints so that the number and its words cannot disagree.
    Tables and sentences (multi-line or non-numeric) carry no words form."""
    out = []
    with open(parity_file, encoding="utf-8") as f:
        for line in f:
            m = SCALAR_MACRO.match(line)
            if not m:
                continue
            name, literal = m.group(1), m.group(2)
            out.append(r"\newcommand{\%sWords}{%s}" % (name, in_words(literal, literal)) + "\n")
    return out


def gen_plain_transfer(tc):
    """The lay Transfer Curve chapter's numbers (#307): one macro per value
    the prose quotes, read from the manifest's transferCurve object, plus
    the words form of every scalar parity-transfer.tex carries."""
    st, bn, fg, mv, dr, o, pr = (tc[k] for k in (
        "stimulus", "binning", "figure", "memoryVerdict", "derotation", "orientation",
        "fundamentalPresence"))
    fs = float(st["sampleRateHz"])
    f0 = float(st["defaultFrequencyHz"])
    spc = fs / f0
    skipped_s = int(st["skipCycles"]) * spc / fs
    total_cycles = float(st["durationS"]) * f0
    ceiling_amplitude = 10 ** (float(st["levelCeilingDBFS"]) / 20)
    macros = {
        "tcNote": tex_escape(st["defaultNote"]),
        "tcNoteHz": num(st["defaultFrequencyHz"]),
        "tcAmplitude": num(st["defaultAmplitude"]),
        "tcLevelDBFS": num(st["defaultLevelDBFS"], 4),
        "tcLevelDBFSRounded": num(int(round(st["defaultLevelDBFS"]))),
        "tcDurationS": num(st["durationS"]),
        "tcPrerollS": num(st["prerollS"]),
        "tcTailS": num(st["tailS"]),
        "tcFadeS": num(st["fadeS"]),
        "tcFadeMs": num(int(round(1000 * st["fadeS"]))),
        "tcSkipCycles": num(st["skipCycles"]),
        "tcSkippedS": num(skipped_s, 2),
        "tcSampleRateHz": num(st["sampleRateHz"]),
        "tcSamplesPerCycle": num(int(round(spc))),
        "tcCycleMs": num(1000 / f0, 3),
        "tcTotalCycles": num(int(round(total_cycles))),
        "tcBinnedCycles": num(int(total_cycles - int(st["skipCycles"]))),
        "tcProbeNotes": ", ".join(tex_escape(n) for n in st["probeNotes"]),
        "tcProbeNoteCount": num(len(st["probeNotes"])),
        "tcRangeNotes": ", ".join(tex_escape(n) for n in st["rangeNotes"]),
        "tcFloorDBFS": num(st["levelFloorDBFS"]),
        "tcCeilingDBFS": num(st["levelCeilingDBFS"]),
        "tcCeilingAmplitude": num(ceiling_amplitude, 1),
        "tcPluginCeilingDBFS": num(st["pluginLevelCeilingDBFS"]),
        "tcBins": num(bn["phaseBins"]),
        "tcStaticGrid": num(fg["staticCurveGridPoints"]),
        "tcLobeFloor": num(fg["minimumLobeAreaFraction"]),
        "tcMemorylessBelow": num(mv["memorylessBelow"]),
        "tcMemorylessBelowPct": num(int(round(100 * mv["memorylessBelow"]))),
        "tcMemoryFrom": num(mv["memoryEffectsFrom"]),
        "tcMemoryFromPct": num(int(round(100 * mv["memoryEffectsFrom"]))),
        "tcDeadZone": num(dr["deadZone"]),
        "tcDeadZonePct": num(int(round(100 * dr["deadZone"]))),
        "tcResidualToleranceRad": num(dr["pairingResidualTolerance"]),
        "tcResidualToleranceDeg": num(math.degrees(dr["pairingResidualTolerance"]), 2),
        "tcMagnitudeFloor": num(dr["fitMagnitudeFloor"]),
        "tcMagnitudeFloorDB": num(dr["fitMagnitudeFloorDB"], 3),
        "tcMinimumTerms": num(dr["minimumFitTerms"]),
        "tcLatticeSignConfidenceRad": num(dr["latticeSignConfidence"]),
        "tcMetricGuardTolerance": num(dr["compensationLoopTolerance"]),
        "tcLockToleranceRad": num(o["halfCycleLockTolerance"]),
        "tcLockToleranceDeg": num(math.degrees(o["halfCycleLockTolerance"]), 2),
        "tcPolarityThreshold": num(o["polarityConfidenceThreshold"]),
        "tcSeparationDB": num(pr["analyzerSeparationDB"]),
    }
    out = ["% GENERATED by gen_docs.py from generated/manifest.json and parity-transfer.tex — do not edit\n",
           "% The lay Transfer Curve chapter's numbers: one macro per quoted value,\n",
           "% derived figures (percent of the box, degrees, seconds) computed from the\n",
           "% manifest's own values, and the words form of every scalar the parity\n",
           "% fragment prints (\\<name>Words beside \\<name>).\n"]
    for name, value in macros.items():
        out.append(r"\newcommand{\%s}{%s}" % (name, value) + "\n")
    out += parity_words_macros(os.path.join(GENERATED, "parity-transfer.tex"))
    write(os.path.join(GENERATED, "plain-transfer.tex"), "".join(out))


# --- The lay Chord IMD chapter's fragment (#307 chapter three) ---------------
# Every number the lay chapter quotes is a macro here, read from the
# manifest's chordIMD object (parameters-imd.tex is a table with no scalar
# macros, and lattice-imd.tex carries only the role grid's two). Derived
# figures — the two grid classes, the collision example, the sub-band
# recipe, the corpus lattice's refused count — are computed from the
# manifest's own values by the same arithmetic the technical chapter
# states, never typed.

INTERVAL_NAMES = {
    1: "a minor second", 2: "a second (or a ninth)", 3: "a minor third",
    4: "a major third", 5: "a fourth", 6: "a tritone", 7: "a fifth",
    8: "a minor sixth", 9: "a major sixth", 10: "a minor seventh",
    11: "a major seventh",
}


def _join_words(items):
    items = list(items)
    if len(items) <= 1:
        return "".join(items)
    return ", ".join(items[:-1]) + " and " + items[-1]


def _khz(rate) -> str:
    """A sample rate in kHz as the guide writes it: 96, 48, 88.2, 44.1."""
    k = rate / 1000.0
    return num(int(k)) if k == int(k) else num(k, 4)


def _enumerate_bins(k1: int, k2: int, bw: float, fs: float, max_order: int):
    """The analyzer's walk (`analyzer.enumerationRule`) on integer bins:
    (m, n, order, bin) for every admitted recipe, the lowest order keeping
    a shared bin."""
    seen = {k1, k2, 0}
    out = []
    limit_bins = 0.95 * fs / 2 / bw
    for order in range(2, max_order + 1):
        for mm in range(-order, order + 1):
            nm = order - abs(mm)
            for nn in (nm, -nm):
                if abs(mm) + abs(nn) != order:
                    continue
                b = mm * k1 + nn * k2
                if not (1 <= b < limit_bins):
                    continue
                if b in seen:
                    continue
                seen.add(b)
                out.append((mm, nn, order, b))
    return out


def _recipe_label(mm: int, nn: int) -> str:
    def part(c, name):
        if c == 0:
            return ""
        mag = "" if abs(c) == 1 else str(abs(c))
        return ("-" if c < 0 else "+") + mag + name
    s = part(mm, "f1") + part(nn, "f2")
    return s.lstrip("+").replace("+", "+").replace("-", "\u2212")


def gen_plain_imd(imd):
    """The lay Chord IMD chapter's numbers: one macro per value the prose
    quotes, read from the manifest's chordIMD object, plus the words form
    of every scalar parity-imd.tex carries."""
    pl, st, lat, wn, an, rs, co, hr = (imd[k] for k in (
        "plan", "stimulus", "lattice", "window", "analyzer", "resolution", "coherence", "harmonicRoles"))
    max_order = int(lat["maxOrder"])
    standard_fs = float(pl["standardSampleRateHz"])
    # The two grid classes: the standard fifth's rows, grouped by the bin
    # pair they land on; class A holds the standard rate.
    fifth = [s for s in lat["snaps"] if s["tier"] == "standard_resolvable"
             and s["label"].startswith("fifth ")]
    by_bins = {}
    for s in fifth:
        by_bins.setdefault((s["binIndex1"], s["binIndex2"]), []).append(s)
    assert len(by_bins) == 2, f"expected two grid classes for the fifth, found {len(by_bins)}"
    class_a = next(rows for rows in by_bins.values() if any(r["sampleRateHz"] == standard_fs for r in rows))
    class_b = next(rows for rows in by_bins.values() if rows is not class_a)

    def class_macros(prefix, rows):
        rows = sorted(rows, key=lambda r: -r["sampleRateHz"])
        head = rows[0]
        return {
            f"imdClass{prefix}Rates": _join_words(_khz(r["sampleRateHz"]) for r in rows) + " kHz",
            f"imdClass{prefix}BinOne": num(head["binIndex1"]),
            f"imdClass{prefix}BinTwo": num(head["binIndex2"]),
            f"imdClass{prefix}CentsOne": num(head["cents1"], 2),
            f"imdClass{prefix}CentsTwo": num(head["cents2"], 2),
            f"imdClass{prefix}Spacing": num(head["spacing"]),
            f"imdClass{prefix}SkirtDepthDB": num(rs["skirtDepthDBAtStandardSpacing"][str(head["spacing"])], 3),
        }

    std_grid = next(g for g in pl["standardGrids"] if g["sampleRateHz"] == standard_fs)
    grid_a = [g for g in pl["standardGrids"] if any(g["sampleRateHz"] == r["sampleRateHz"] for r in class_a)]
    grid_b = [g for g in pl["standardGrids"] if any(g["sampleRateHz"] == r["sampleRateHz"] for r in class_b)]
    assert len({round(g["stimulusDurationS"], 6) for g in grid_a}) == 1
    assert len({round(g["stimulusDurationS"], 6) for g in grid_b}) == 1
    corpus_grid = pl["fallbackGrids"][0]
    corpus_snap = next(s for s in lat["snaps"] if s["fftLength"] == corpus_grid["fftLength"]
                       and s["sampleRateHz"] == corpus_grid["sampleRateHz"] and s["label"].startswith("fifth"))
    # The collision example, derived from the bound the technical chapter
    # states: a + b >= 2K + 1 is clean, so the sum one below it collides,
    # and 1 : (2K - 1) is the ratio at that sum.
    assert int(lat["minimumReducedSum"]) == 2 * max_order + 1
    colliding_sum = int(lat["minimumReducedSum"]) - 1
    # The sub-band recipe on the standard grid: the enumerated recipe with
    # the smallest positive bin, which the shipped fifth puts under the
    # band's low edge (asserted, so the sentence cannot outlive the fact).
    head_a = sorted(class_a, key=lambda r: -r["sampleRateHz"])[0]
    bw_a = standard_fs / std_grid["fftLength"]
    recipes_a = _enumerate_bins(head_a["binIndex1"], head_a["binIndex2"], bw_a, standard_fs, max_order)
    sub = min(recipes_a, key=lambda r: r[3])
    sub_hz = sub[3] * bw_a
    assert sub_hz < imd["audibleBand"]["lowHz"], "the lowest recipe is not under the band's low edge"
    # The corpus lattice: recipes inside the neighbourhood of a note or DC.
    bw_c = corpus_grid["sampleRateHz"] / corpus_grid["fftLength"]
    recipes_c = _enumerate_bins(corpus_snap["binIndex1"], corpus_snap["binIndex2"], bw_c,
                                corpus_grid["sampleRateHz"], max_order)
    nb = int(rs["playedToneNeighbourhoodBins"])
    near_note = [r for r in recipes_c if min(abs(r[3] - corpus_snap["binIndex1"]), abs(r[3] - corpus_snap["binIndex2"])) <= nb]
    near_dc = [r for r in recipes_c if r[3] <= nb and r not in near_note]
    near_note_offsets = sorted({min(abs(r[3] - corpus_snap["binIndex1"]), abs(r[3] - corpus_snap["binIndex2"])) for r in near_note})
    assert len(near_note_offsets) == 1, f"the corpus recipes beside the notes sit at several offsets: {near_note_offsets}"
    assert len(near_dc) == 1
    # Numbers the manifest carries only inside a rule string are read from
    # there rather than typed (the HD writer's minimum-half-width precedent).
    gate_factor = int(re.search(r"amplitude > (\d+)", an["aboveFloorRule"]).group(1))
    older_bias = re.search(r"measured ([0-9.]+) dB mean bias", an["levelRule"]).group(1)
    detector_bins = 2 * 2 * int(co["maximumDetectorOffsetBins"])
    excess = co["expectedNoiseExcessDB"]
    assert str(detector_bins) in excess, f"no noise excess for {detector_bins} bins"
    legacy_bins = next(int(k) for k in excess if int(k) != detector_bins)
    table = hr["tables"][0]
    assert table["lowerNote"] == pl["defaultNote1"] and table["upperNote"] == pl["defaultNote2"]
    tone_dbfs = 20 * math.log10(pl["defaultPeakAmplitude"] / 2)
    macros = {
        "imdNoteOne": tex_escape(pl["defaultNote1"]),
        "imdNoteTwo": tex_escape(pl["defaultNote2"]),
        "imdNoteOneHz": num(table["lowerNominalHz"], 4),
        "imdNoteTwoHz": num(table["upperNominalHz"], 4),
        "imdPeakAmplitude": num(pl["defaultPeakAmplitude"]),
        "imdPeakDBFS": num(pl["defaultPeakDBFS"], 3),
        "imdToneDBFS": num(tone_dbfs, 3),
        "imdFadeMs": num(int(round(1000 * st["fadeS"]))),
        "imdSettleS": num(wn["settleS"]),
        "imdSupportedRatesKHz": _join_words(_khz(r) for r in pl["supportedSampleRatesHz"]),
        "imdStandardRateKHz": _khz(standard_fs),
        "imdStandardLengthPower": num(int(math.log2(pl["standardFFTLength"]))),
        "imdStandardLength": num(pl["standardFFTLength"]),
        "imdBinWidthHz": num(std_grid["binWidthHz"], 2),
        "imdWindowS": num(std_grid["windowLength"] / standard_fs, 3),
        "imdStimulusClassAS": num(grid_a[0]["stimulusDurationS"], 3),
        "imdStimulusClassBS": num(grid_b[0]["stimulusDurationS"], 3),
        "imdRatioA": num(lat["standardRatioA"]),
        "imdRatioB": num(lat["standardRatioB"]),
        "imdRatioSum": num(int(lat["standardRatioA"]) + int(lat["standardRatioB"])),
        "imdStandardIntervalCents": num(lat["standardIntervalCents"], 4),
        "imdRequestedIntervalCents": num(lat["requestedIntervalCents"], 4),
        "imdIntervalFlatCents": num(lat["requestedIntervalCents"] - lat["standardIntervalCents"], 2),
        "imdSurvivorCount": num(lat["standardSurvivorCount"]),
        "imdRecipeCount": num(an["recipeCount"]),
        "imdMaxOrder": num(max_order),
        "imdNeighbourhoodBins": num(nb),
        "imdResolvableSpacing": num(lat["resolvableSpacingBins"]),
        "imdCentsBudget": num(lat["toneCentsBudget"]),
        "imdMinimumReducedSum": num(lat["minimumReducedSum"]),
        "imdCollidingRatio": f"1 : {num(2 * max_order - 1)}",
        "imdCollidingSum": num(colliding_sum),
        "imdGateFactor": num(gate_factor),
        "imdGateDB": num(an["aboveFloorDB"], 3),
        "imdOlderReadBiasDB": older_bias,
        "imdLocalFloorInnerBins": num(an["localFloorInnerOffsetBins"]),
        "imdLocalFloorSpanHz": num(an["localFloorSpanHz"], 2),
        "imdLocalFloorOuterBins": num(std_grid["localFloorOuterOffsetBins"]),
        "imdLocalFloorMinimumOffsets": num(an["localFloorMinimumOffsets"]),
        "imdMinimumFloorSamples": num(rs["minimumFloorSamples"]),
        "imdPartnerToleranceDB": num(rs["partnerToleranceDB"]),
        "imdBarDB": num(co["thresholdOverFloorDB"]),
        "imdDetectorMaxOffset": num(co["maximumDetectorOffsetBins"]),
        "imdDetectorBinCount": num(detector_bins),
        "imdLegacyBinCount": num(legacy_bins),
        "imdNoiseExcessDetectorDB": num(excess[str(detector_bins)], 2),
        "imdNoiseExcessLegacyDB": num(excess[str(legacy_bins)], 2),
        "imdMinimumClearanceBins": num(co["minimumClearanceBins"]),
        "imdProductSkirtMarginDB": num(co["productSkirtMarginDB"]),
        "imdCeilingNearestDBc": num(co["productCeilingsDBcAtStandardSpacing"][0], 3),
        "imdCeilingWidestDBc": num(co["productCeilingsDBcAtStandardSpacing"][-1], 3),
        "imdPitchToleranceCents": num(hr["pitchToleranceCents"]),
        "imdAddedColourNames": _join_words(INTERVAL_NAMES[c] for c in hr["addedColourSemitoneClasses"]),
        "imdFifthJustRatio": f"{num(table['ratioB'])} : {num(table['ratioA'])}",
        "imdFifthGridHz": num(table["gridHz"]),
        "imdAudibleLowHz": num(imd["audibleBand"]["lowHz"]),
        "imdAudibleHighHz": num(imd["audibleBand"]["highHz"]),
        "imdSubBandRecipe": tex_escape(_recipe_label(sub[0], sub[1])),
        "imdSubBandHz": num(sub_hz, 2),
        "imdSubBandBins": num(sub[3]),
        "imdCorpusLengthPower": num(int(math.log2(corpus_grid["fftLength"]))),
        "imdCorpusWindowS": num(corpus_grid["windowLength"] / corpus_grid["sampleRateHz"], 2),
        "imdCorpusBinOne": num(corpus_snap["binIndex1"]),
        "imdCorpusBinTwo": num(corpus_snap["binIndex2"]),
        "imdCorpusSpacing": num(corpus_snap["spacing"]),
        "imdCorpusRatioA": num(corpus_snap["reducedA"]),
        "imdCorpusRatioB": num(corpus_snap["reducedB"]),
        "imdCorpusNearNoteCount": num(len(near_note)),
        "imdCorpusNearNoteOffset": num(near_note_offsets[0]),
        "imdCorpusNearDCOffset": num(near_dc[0][3]),
    }
    macros.update(class_macros("A", class_a))
    macros.update(class_macros("B", class_b))
    out = ["% GENERATED by gen_docs.py from generated/manifest.json and parity-imd.tex — do not edit\n",
           "% The lay Chord IMD chapter's numbers: one macro per quoted value, the\n",
           "% derived figures (the two grid classes, the collision example, the\n",
           "% sub-band recipe, the corpus lattice's refusals) computed from the\n",
           "% manifest's own values, and the words form of every scalar the parity\n",
           "% fragment prints (\\<name>Words beside \\<name>).\n"]
    for name, value in macros.items():
        out.append(r"\newcommand{\%s}{%s}" % (name, value) + "\n")
    out += parity_words_macros(os.path.join(GENERATED, "parity-imd.tex"))
    write(os.path.join(GENERATED, "plain-imd.tex"), "".join(out))


# --- The lay companion's fragment ------------------------------------------
# explained.tex quotes numbers through these macros and this table and types
# none of them (the parity macros in parity-hd.tex serve both registers).

NOTE_NAMES = ["C", "C\\#", "D", "D\\#", "E", "F", "F\\#", "G", "G\\#", "A", "A\\#", "B"]


def nearest_note(hz: float) -> str:
    """The nearest equal-tempered note name, A4 = 440 Hz (the convention the
    guide's tuning page states) — a naming aid beside a frequency, never a
    measured quantity."""
    semitones = int(round(12 * math.log2(hz / 440.0)))
    index = (semitones + 9) % 12          # 0 = C
    octave = 4 + (semitones + 9) // 12
    return f"{NOTE_NAMES[index]}{octave}"


def gen_plain(m):
    st, ex, rd, va, gr, fl, av, pr, sh = (m[k] for k in (
        "stimulus", "extraction", "reading", "validity", "grids", "floor", "averaging",
        "fundamentalPresence", "shaping"))
    delays = st["harmonicDelaysS"]
    tops = va["maxValidFundamentalHz"]
    macros = {
        "hdStartHz": num(st["startHz"]),
        "hdEndHz": num(st["endHz"]),
        "hdRequestedDurationS": num(st["requestedDurationS"]),
        "hdActualDurationS": num(st["durationS"], 4),
        "hdSampleRateHz": num(st["sampleRateHz"]),
        "hdAmplitude": num(st["amplitude"]),
        "hdRateConstantS": num(st["rateConstantS"]),
        "hdSyncCycles": num(st["synchronizationCycles"]),
        "hdFadeInS": num(st["fadeInS"]),
        "hdFadeOutS": num(st["fadeOutS"]),
        "hdExcitedBottomHz": num(st["excitedBandBottomHz"], 4),
        "hdExcitedTopHz": num(st["excitedBandTopHz"], 5),
        "hdHarmonicCount": num(ex["harmonicCount"]),
        "hdDelayTwoS": num(delays[1], 4),
        "hdDelayThreeS": num(delays[2], 4),
        "hdDelayNineS": num(delays[8], 4),
        "hdWindowCapS": num(ex["maxWindowHalfWidthS"]),
        "hdWindowFullS": num(ex["windows"][0]["windowS"], 3),
        "hdWindowNineS": num(ex["windows"][8]["windowS"], 4),
        "hdBinWidthHz": num(rd["binWidthHz"], 3),
        "hdTopNoteFiveHz": num(tops[4], 4),
        "hdTopNoteNineHz": num(tops[8], 4),
        "hdTopNoteNineName": nearest_note(tops[8]),
        "hdAudibleLowHz": num(m["audibleBand"]["lowHz"]),
        "hdAudibleHighHz": num(m["audibleBand"]["highHz"]),
        "hdThdGridLowHz": num(gr["thdCurve"]["lowHz"], 3),
        "hdThdGridPoints": num(gr["thdCurve"]["pointCount"]),
        "hdThdGridRequested": num(gr["thdCurve"]["requestedPointCount"]),
        "hdSeparationDB": num(pr["analyzerSeparationDB"]),
        "hdShapedSNRDB": num(sh["shapedSNRDB"]),
        "hdShapingWindowSamples": num(sh["windowSampleCount"]),
        "hdUnshapedCoherence": num(sh["unshapedCoherence"], 2),
        "hdUnshapedScatterDB": num(sh["unshapedScatterDB"], 2),
        "hdDefaultAverages": num(av["defaultAverages"]),
        "hdOfferedAverages": ", ".join(num(x) for x in av["offeredAverages"]),
        "hdAveragingFourDB": num(-fl["averagingAdjustmentDB"]["4"], 2),
        "hdAveragingEightDB": num(-fl["averagingAdjustmentDB"]["8"], 2),
        "hdGapS": num(av["interSweepGapS"]),
        # The minimum half-width is a literal inside the analyzer (the technical
        # table says so); the manifest carries it inside the rule string, so it
        # is read from there rather than typed.
        "hdMinimumHalfWidthSamples": num(int(re.search(r"\b(\d+) samples", ex["minimumHalfWidthRule"]).group(1))),
    }
    out = ["% GENERATED by gen_docs.py from generated/manifest.json — do not edit\n",
           "% The lay companion's numbers: one macro per quoted value, and the\n",
           "% per-harmonic table in plain words. Note names are the nearest\n",
           "% equal-tempered note, A4 = 440 Hz.\n"]
    for name, value in macros.items():
        out.append(r"\newcommand{\%s}{%s}" % (name, value) + "\n")
    out.append(r"\newcommand{\hdPlainWindows}{" + "\n")
    out.append(r"\begin{tabular}{@{}rrrrl@{}}" + "\n")
    out.append(r"\toprule harmonic & arrives earlier by (s) & slice kept (s) & readable up to (Hz) & nearest note \\ \midrule" + "\n")
    for row, top in zip(ex["windows"], tops):
        k = row["order"]
        out.append(f"{k} & {num(row['delayS'], 4)} & {num(row['windowS'], 4)} & {num(top, 6)} & {nearest_note(top)} \\\\\n")
    out.append(r"\bottomrule" + "\n" + r"\end{tabular}" + "\n}\n")
    # The words form of every scalar parity-hd.tex prints (#307's rider):
    # \paritySwiftToleranceWords beside \paritySwiftTolerance, and so on.
    out += parity_words_macros(os.path.join(GENERATED, "parity-hd.tex"))
    write(os.path.join(GENERATED, "plain-hd.tex"), "".join(out))


def main(argv=None):
    p = argparse.ArgumentParser()
    p.add_argument("--no-parity", action="store_true", help="skip the parity table (no Swift tool needed)")
    args = p.parse_args(argv)
    os.makedirs(GENERATED, exist_ok=True)
    m = hd.load_manifest()
    with open(hd.DEFAULT_MANIFEST, encoding="utf-8") as f:
        whole = json.load(f)
    transfer = whole["transferCurve"]
    gen_terms(load_terms())
    gen_parameters(m)
    gen_windows(m)
    gen_parameters_transfer(transfer)
    gen_parameters_imd(whole["chordIMD"])
    gen_lattice_imd(whole["chordIMD"])
    gen_parameters_journey(whole["gainMap"])
    gen_residue_journey(whole["gainMap"])
    if not args.no_parity:
        gen_parity(m)
        gen_parity_transfer(transfer)
        gen_parity_imd(whole)
        gen_parity_journey(whole)
    # The plain writers run last: their words-form macros read the parity
    # fragments as this run left them (the committed ones under --no-parity).
    gen_plain(m)
    gen_plain_transfer(transfer)
    gen_plain_imd(whole["chordIMD"])
    return 0


if __name__ == "__main__":
    sys.exit(main())
